// Generated by installer/cmd/usos-i18n-gen from installer/internal/i18n/locales. Do not edit.
// English is built in; lang.bin on the ESP carries only the chosen language.

pub const Key = enum(u16) {
    action_blocked,
    action_chainload,
    action_efi,
    action_hint,
    action_iso,
    action_vhdboot,
    action_wimboot,
    action_xp,
    badge_experimental,
    badge_ready,
    badge_recommended,
    badge_tested_in_vm,
    badge_unavailable,
    bios_backend_failed_line1,
    bios_backend_failed_title,
    bios_hardware,
    bios_loading,
    bios_loading_files,
    bios_no_images_title,
    bios_setup_help,
    bios_setup_progress,
    bios_setup_reading,
    bios_setup_title,
    bios_setup_failed_line1,
    bios_setup_failed_line2,
    bios_setup_failed_line3,
    bios_setup_failed_title,
    bios_starting_installer,
    bios_xp_resume_continue,
    bios_xp_resume_line1,
    bios_xp_resume_line2,
    bios_xp_resume_line3,
    bios_xp_resume_line4,
    bios_xp_resume_title,
    category_beta,
    category_beta_desc,
    category_dos_desc,
    category_linux_desc,
    category_power,
    category_power_desc,
    category_utilities,
    category_utilities_desc,
    category_windows_desc,
    chainload_line1,
    chainload_line2,
    chainload_title,
    day_0,
    day_1,
    day_2,
    day_3,
    day_4,
    day_5,
    day_6,
    dos_confirm_go,
    dos_confirm_note1,
    dos_confirm_note2,
    dos_confirm_title,
    dos_disk,
    dos_disk_mbr,
    dos_layout,
    dos_msdos_install,
    dos_msdos_note1,
    dos_msdos_note2,
    dos_msdos_run,
    dos_msdos_subtitle,
    dos_no_disks,
    dos_pick_fat16,
    dos_pick_fat32,
    dos_pick_repair,
    dos_repair_apply,
    dos_repair_detail,
    dos_repair_note1,
    dos_repair_note2,
    dos_repair_title,
    dos_size_note1,
    dos_size_note2,
    dos_size_title,
    dos_w98_install,
    dos_w98_repair,
    dos_w98_subtitle,
    efi_line1,
    efi_title,
    error_catalog_line1,
    error_catalog_line2,
    error_catalog_title,
    error_efi,
    error_firmware_line1,
    error_firmware_title,
    error_iso,
    error_preparation,
    error_stopped,
    error_unsupported_line1,
    error_unsupported_title,
    error_xp,
    handoff_bootmgr,
    handoff_commit,
    handoff_line1,
    handoff_line2,
    handoff_ntfs,
    handoff_setup,
    handoff_title,
    handoff_transfer,
    handoff_verify,
    handoff_work,
    header_build,
    header_no_mouse,
    header_subtitle,
    help_auto_title,
    help_auto_iso_line1,
    help_auto_iso_line2,
    help_chainload_line1,
    help_chainload_line2,
    help_chainload_title,
    help_disk_image_line1,
    help_disk_image_line2,
    help_disk_image_title,
    help_efi_line1,
    help_efi_line2,
    help_efi_title,
    help_floppy_line1,
    help_floppy_line2,
    help_floppy_title,
    help_generic_line1,
    help_generic_line2,
    help_iso_line1,
    help_iso_line2,
    help_iso_title,
    help_memdisk_line1,
    help_memdisk_line2,
    help_memdisk_title,
    help_setup_line1,
    help_setup_line2,
    help_setup_title,
    help_vhdboot_line1,
    help_vhdboot_line2,
    help_vhdboot_title,
    help_wimboot_line1,
    help_wimboot_line2,
    help_wimboot_title,
    help_win7_wimboot_line1,
    help_win7_wimboot_line2,
    help_win7_wimboot_title,
    help_windows_setup_title,
    images_none_line1,
    images_none_line2,
    images_subtitle,
    images_title,
    input_test_help,
    input_test_title,
    iso_drivers,
    iso_external_pe,
    iso_hybrid_pe,
    iso_loading_wim,
    iso_reading,
    iso_stage_1,
    iso_stage_2,
    iso_stage_3,
    iso_title,
    iso_validating,
    key_back,
    key_boot_method,
    key_cancel,
    key_confirm,
    key_continue,
    key_diagnostics,
    key_next,
    key_open,
    key_power,
    key_power_off,
    key_run,
    key_scroll,
    key_select,
    key_size,
    key_start,
    key_summary,
    key_use,
    key_usos_menu,
    language_name,
    menu_subtitle,
    menu_title,
    method_auto_chainload,
    method_auto_dos_setup,
    method_auto_efi,
    method_auto_iso,
    method_auto_msdos,
    method_auto_slitaz,
    method_auto_vhdboot,
    method_auto_wimboot,
    method_auto_win2000,
    method_auto_windows_setup,
    method_auto_xp,
    method_auto_xp_uefi,
    method_automatic,
    method_chainload,
    method_disk_image,
    method_floppy_image,
    methods_none,
    methods_subtitle,
    methods_title,
    notice_backend_line1,
    notice_backend_line2,
    notice_no_image_line1,
    notice_no_image_title,
    power_apm_line1,
    power_apm_line2,
    power_firmware,
    power_firmware_error_line1,
    power_firmware_error_title,
    power_firmware_unsupported,
    power_input_test,
    power_restart,
    power_shutdown,
    power_subtitle,
    power_title,
    prep_copy_note,
    prep_diag_title,
    prep_diag_truncated,
    prep_env_title,
    prep_eta,
    prep_footer_done,
    prep_footer_running,
    prep_loader_ready,
    prep_next_boot,
    prep_remove_usb,
    prep_request_saved,
    prep_return_boot,
    prep_speed,
    prep_stage_1,
    prep_stage_2,
    prep_stage_3,
    prep_stage_4,
    prep_stage_5,
    prep_starting,
    prep_status_done,
    prep_status_failed,
    prep_status_running,
    prep_status_waiting,
    prep_step,
    prep_title,
    prep_xp_disks,
    splash_images,
    splash_loading,
    splash_starting,
    summary_answer_file,
    summary_boot_pe,
    summary_boot_source,
    summary_disk,
    summary_driver_inventory,
    summary_drivers,
    summary_error,
    summary_image,
    summary_inf_count,
    summary_iso_case,
    summary_iso_inspection,
    summary_method,
    summary_no_drivers,
    summary_preparation,
    summary_source,
    summary_subtitle,
    summary_system,
    summary_target_support,
    summary_title,
    summary_unavailable,
    summary_usb,
    summary_vista_case,
    summary_vista_support,
    summary_vista_usb,
    summary_xp_disk,
    summary_xp_no_unattended,
    summary_xp_preparation,
    summary_xp_source,
    system_copy_to,
    system_image_count,
    system_no_image,
    system_ready,
    system_requires_bios,
    system_requires_bios_detail,
    system_requires_uefi,
    system_requires_uefi_detail,
    system_unavailable,
    system_unavailable_detail,
    systems_subtitle,
    unattended_file_detail,
    unattended_none,
    unattended_none_detail,
    unattended_subtitle,
    unattended_title,
    utilities_freedos_desc,
    utilities_hardware_desc,
    utilities_none_line1,
    utilities_none_line2,
    utilities_none_title,
    utility_unavailable,
    wait,
    wait_usb,
};

/// FNV-1a 32 of the key names stored in lang.bin (without the "boot." prefix).
pub const hashes = [_]u32{
    0xb9a53ded, // action.blocked
    0x67542164, // action.chainload
    0x4743492f, // action.efi
    0x8d1362d2, // action.hint
    0xf7710f28, // action.iso
    0x351f129f, // action.vhdboot
    0x3979b582, // action.wimboot
    0x45058703, // action.xp
    0xe81a21c0, // badge.experimental
    0x70416b89, // badge.ready
    0xc1e902c9, // badge.recommended
    0xa07f0359, // badge.tested_in_vm
    0xf502a3ec, // badge.unavailable
    0x1dc0f3e7, // bios.backend_failed.line1
    0x175fbc90, // bios.backend_failed.title
    0xfbb764e0, // bios.hardware
    0x41fa93a4, // bios.loading
    0x993dc1bc, // bios.loading_files
    0x7724e692, // bios.no_images.title
    0xffdc61f6, // bios.setup.help
    0xd454f13a, // bios.setup.progress
    0xb086080f, // bios.setup.reading
    0xe960c5dd, // bios.setup.title
    0xd6ba7a18, // bios.setup_failed.line1
    0xd9ba7ed1, // bios.setup_failed.line2
    0xd8ba7d3e, // bios.setup_failed.line3
    0xfa32ec43, // bios.setup_failed.title
    0x7ea092f3, // bios.starting_installer
    0x1f902dd5, // bios.xp_resume.continue
    0x3eb756f5, // bios.xp_resume.line1
    0x3bb7523c, // bios.xp_resume.line2
    0x3cb753cf, // bios.xp_resume.line3
    0x39b74f16, // bios.xp_resume.line4
    0xce8a7b02, // bios.xp_resume.title
    0xdfc5a04f, // category.beta
    0x50adb2ee, // category.beta.desc
    0xc4dcd124, // category.dos.desc
    0xf91b310c, // category.linux.desc
    0x47a1786e, // category.power
    0x3595e4b1, // category.power.desc
    0x0443aa4f, // category.utilities
    0x977550ee, // category.utilities.desc
    0xb473adb5, // category.windows.desc
    0xfc4d4ef9, // chainload.line1
    0xf94d4a40, // chainload.line2
    0xb38e898e, // chainload.title
    0xe039545b, // day.0
    0xdf3952c8, // day.1
    0xe2395781, // day.2
    0xe13955ee, // day.3
    0xe4395aa7, // day.4
    0xe3395914, // day.5
    0xe6395dcd, // day.6
    0xebddf16d, // dos.confirm.go
    0x44551082, // dos.confirm.note1
    0x43550eef, // dos.confirm.note2
    0x8aa8f83f, // dos.confirm.title
    0x6081ba68, // dos.disk
    0xf3336024, // dos.disk_mbr
    0x5987730b, // dos.layout
    0x6ca16ba4, // dos.msdos.install
    0xc71281a8, // dos.msdos.note1
    0xca128661, // dos.msdos.note2
    0x8c98b19e, // dos.msdos.run
    0x84ecd0dd, // dos.msdos.subtitle
    0xb5cfa773, // dos.no_disks
    0x1cf46ed6, // dos.pick.fat16
    0xa8f9c868, // dos.pick.fat32
    0x095414a3, // dos.pick.repair
    0x636cf32a, // dos.repair.apply
    0xc5fe23b3, // dos.repair.detail
    0x68d075cd, // dos.repair.note1
    0x65d07114, // dos.repair.note2
    0xfbdbe764, // dos.repair.title
    0x32bc1fa5, // dos.size.note1
    0x2fbc1aec, // dos.size.note2
    0xfdb391bc, // dos.size.title
    0x98538446, // dos.w98.install
    0xaaa58af6, // dos.w98.repair
    0xca53fd63, // dos.w98.subtitle
    0x23541dfa, // efi.line1
    0xf4cad9b1, // efi.title
    0x35820aab, // error.catalog.line1
    0x36820c3e, // error.catalog.line2
    0x9807296c, // error.catalog.title
    0x31ce0c49, // error.efi
    0x1ec31a4f, // error.firmware.line1
    0xaeecd888, // error.firmware.title
    0x5f16a066, // error.iso
    0xacc67c62, // error.preparation
    0xfe82b516, // error.stopped
    0x96c6d0e3, // error.unsupported.line1
    0x471635f4, // error.unsupported.title
    0x74a11b6d, // error.xp
    0x096158f9, // handoff.bootmgr
    0x12a81bf8, // handoff.commit
    0x23c3a3ee, // handoff.line1
    0x22c3a25b, // handoff.line2
    0x1020d73c, // handoff.ntfs
    0x715fcb22, // handoff.setup
    0x8496255d, // handoff.title
    0x40ae76c2, // handoff.transfer
    0x467b2d38, // handoff.verify
    0x3359246c, // handoff.work
    0x9d2e5b72, // header.build
    0x2b0a3151, // header.no_mouse
    0xf19fe29e, // header.subtitle
    0xf6a9e837, // help.auto.title
    0x5353cd3a, // help.auto_iso.line1
    0x5253cba7, // help.auto_iso.line2
    0xc18f8922, // help.chainload.line1
    0xc08f878f, // help.chainload.line2
    0xb6117989, // help.chainload.title
    0x1e171c68, // help.disk_image.line1
    0x21172121, // help.disk_image.line2
    0x5dbfe7f3, // help.disk_image.title
    0x6d5238ed, // help.efi.line1
    0x6a523434, // help.efi.line2
    0xf06fc68a, // help.efi.title
    0x7e1ee4d1, // help.floppy.line1
    0x7b1ee018, // help.floppy.line2
    0x4ca057b6, // help.floppy.title
    0x65002e6a, // help.generic.line1
    0x64002cd7, // help.generic.line2
    0xb898037a, // help.iso.line1
    0xb79801e7, // help.iso.line2
    0x8a0ebf31, // help.iso.title
    0x10d398e7, // help.memdisk.line1
    0x11d39a7a, // help.memdisk.line2
    0x0a726190, // help.memdisk.title
    0x0f150192, // help.setup.line1
    0x0e14ffff, // help.setup.line2
    0x5290dd59, // help.setup.title
    0xbb1cf439, // help.vhdboot.line1
    0xb81cef80, // help.vhdboot.line2
    0x1c220d4e, // help.vhdboot.title
    0x1b96152c, // help.wimboot.line1
    0x1e9619e5, // help.wimboot.line2
    0x212fbc8f, // help.wimboot.title
    0x4bf3a4b0, // help.win7_wimboot.line1
    0x4ef3a969, // help.win7_wimboot.line2
    0xc579f0eb, // help.win7_wimboot.title
    0x18900e83, // help.windows_setup.title
    0xa083adfa, // images.none.line1
    0x9f83ac67, // images.none.line2
    0x7192a123, // images.subtitle
    0x403d0617, // images.title
    0x3f42c8f5, // input_test.help
    0xeccf9134, // input_test.title
    0x646697d7, // iso.drivers
    0x2482ded7, // iso.external_pe
    0x244161e4, // iso.hybrid_pe
    0x9f2ad69c, // iso.loading_wim
    0xac900584, // iso.reading
    0xd364e7f3, // iso.stage.1
    0xd464e986, // iso.stage.2
    0xd564eb19, // iso.stage.3
    0x1fdc1e96, // iso.title
    0xd22ab261, // iso.validating
    0x5bf90715, // key.back
    0x1282304e, // key.boot_method
    0xeee5a29c, // key.cancel
    0x70bcc806, // key.confirm
    0x6528007f, // key.continue
    0x7b94114e, // key.diagnostics
    0x5ee1de9b, // key.next
    0x7516d1e6, // key.open
    0x5c531bb7, // key.power
    0x983f3e9d, // key.power_off
    0x3210481f, // key.run
    0xa9502577, // key.scroll
    0xd858a6be, // key.select
    0xee6c2be7, // key.size
    0xc4db73e6, // key.start
    0x01545ee2, // key.summary
    0xce8206d1, // key.use
    0xaf281282, // key.usos_menu
    0x5aa9bbcc, // language.name
    0x041dd1a8, // menu.subtitle
    0x82ff555a, // menu.title
    0x9166eacb, // method.auto_chainload
    0xac512b2e, // method.auto_dos_setup
    0xcf4f3104, // method.auto_efi
    0x3b5c2e47, // method.auto_iso
    0xdf251230, // method.auto_msdos
    0xdc54235f, // method.auto_slitaz
    0xd0d5afbc, // method.auto_vhdboot
    0xaaec70e9, // method.auto_wimboot
    0x1fcc2a9a, // method.auto_win2000
    0xabbaa3a1, // method.auto_windows_setup
    0x4c33f486, // method.auto_xp
    0x34663e98, // method.auto_xp_uefi
    0x693c9e3d, // method.automatic
    0x92d38fcf, // method.chainload
    0xa9de181d, // method.disk_image
    0x95f4de1e, // method.floppy_image
    0x9593c94b, // methods.none
    0x88241669, // methods.subtitle
    0x616e0619, // methods.title
    0x48a2a970, // notice.backend.line1
    0x4ba2ae29, // notice.backend.line2
    0xe2e6f917, // notice.no_image.line1
    0x2b57a9a0, // notice.no_image.title
    0x4542418f, // power.apm.line1
    0x46424322, // power.apm.line2
    0x69b9a301, // power.firmware
    0x8aa47bc2, // power.firmware.error.line1
    0xe35e84a9, // power.firmware.error.title
    0x80093ad8, // power.firmware.unsupported
    0x94bdee21, // power.input_test
    0x77e5c8b3, // power.restart
    0x61976512, // power.shutdown
    0x267882fc, // power.subtitle
    0xe7aba2de, // power.title
    0x14cb484e, // prep.copy_note
    0x91b207e7, // prep.diag.title
    0x051fa553, // prep.diag.truncated
    0x0623d95f, // prep.env.title
    0xec0a0b0c, // prep.eta
    0xfa71f86f, // prep.footer.done
    0x6c030272, // prep.footer.running
    0x48d1e0f7, // prep.loader_ready
    0x848caac2, // prep.next_boot
    0xc7e6fd7d, // prep.remove_usb
    0xce2deea5, // prep.request_saved
    0x6a7e2473, // prep.return_boot
    0x6f11970f, // prep.speed
    0x7e12c69f, // prep.stage.1
    0x7f12c832, // prep.stage.2
    0x8012c9c5, // prep.stage.3
    0x7912bec0, // prep.stage.4
    0x7a12c053, // prep.stage.5
    0x416d9ce0, // prep.starting
    0x96053b70, // prep.status.done
    0x739921d5, // prep.status.failed
    0x0773ae1f, // prep.status.running
    0x5de2d29f, // prep.status.waiting
    0x5a2661f6, // prep.step
    0x84ce2712, // prep.title
    0x87155e69, // prep.xp_disks
    0x4f9583c2, // splash.images
    0x35ce4a04, // splash.loading
    0x790f2c74, // splash.starting
    0x21b7d2fc, // summary.answer_file
    0x793c0723, // summary.boot_pe
    0xae5be5f9, // summary.boot_source
    0x4c709436, // summary.disk
    0xc97409c2, // summary.driver_inventory
    0xacfd5f5a, // summary.drivers
    0x5fb166d7, // summary.error
    0xc7a77b9c, // summary.image
    0xfbb93592, // summary.inf_count
    0xa67ee0dd, // summary.iso_case
    0x23a9357f, // summary.iso_inspection
    0x3ed2d6ee, // summary.method
    0xe8143028, // summary.no_drivers
    0x92637c78, // summary.preparation
    0x46c71b92, // summary.source
    0xa12382cb, // summary.subtitle
    0xa6031186, // summary.system
    0x9be682aa, // summary.target_support
    0xd56f468f, // summary.title
    0x0c17e473, // summary.unavailable
    0x38417087, // summary.usb
    0x8e042d81, // summary.vista_case
    0xa0987638, // summary.vista_support
    0x1e3154b1, // summary.vista_usb
    0xe262ce65, // summary.xp_disk
    0xf02f95da, // summary.xp_no_unattended
    0xedd282b9, // summary.xp_preparation
    0x6dfb98bd, // summary.xp_source
    0x6fd0eb35, // system.copy_to
    0x4961b793, // system.image_count
    0x2a578ca3, // system.no_image
    0xd3048155, // system.ready
    0xab6c36c8, // system.requires_bios
    0x47e54d83, // system.requires_bios.detail
    0xeb00f308, // system.requires_uefi
    0xc483f543, // system.requires_uefi.detail
    0x31aec0c8, // system.unavailable
    0xa6ba9b83, // system.unavailable.detail
    0xab5ff4f5, // systems.subtitle
    0x42cdb840, // unattended.file.detail
    0x9b91564d, // unattended.none
    0x16e5e868, // unattended.none.detail
    0x0404a4d7, // unattended.subtitle
    0x117edf4b, // unattended.title
    0x90427850, // utilities.freedos.desc
    0xbe35b4e2, // utilities.hardware.desc
    0x89ec8a66, // utilities.none.line1
    0x88ec88d3, // utilities.none.line2
    0x638b0125, // utilities.none.title
    0x30ddf187, // utility.unavailable
    0x892e4ca0, // wait
    0x3e1f8ab9, // wait_usb
};

/// False for strings only the UEFI menu shows (left out of the BIOS Core).
pub const bios = [_]bool{
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    true,
    true,
    false,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    true,
    true,
};

pub const english = [_][]const u8{
    "Start is not possible with these settings",
    "Prepare and chainload",
    "Start the EFI application",
    "Press Enter or click the button to start.",
    "Load the Windows ISO",
    "Prepare native VHD/VHDX boot",
    "Build and boot the WIM environment",
    "Prepare the Windows XP installation",
    "Experimental",
    "Ready",
    "Recommended",
    "Tested in VM",
    "Unavailable",
    "The selected Legacy backend returned an error.",
    "Boot method failed: {0}",
    "Hardware & SMART",
    "Loading environment",
    "Loading startup files - {0}%",
    "No images: {0}",
    "Loading Windows Setup into memory. Keep the USB drive connected.",
    "Loading Windows Setup - {0}%",
    "Reading the installer from USB",
    "Starting Windows Setup",
    "Windows Setup could not be loaded.",
    "The prepared installation files were kept on the USB drive.",
    "Restart to try again, or press Esc to return to the USOS menu.",
    "Windows Setup - start failed",
    "Starting Windows installer",
    "Continue XP",
    "A Windows XP installation was prepared on a target disk.",
    "After Text Mode has copied files and restarted, press Enter.",
    "USOS will verify that disk and restore its startup code.",
    "Then remove USOS and start the target disk to continue Setup.",
    "Windows XP - continue installation",
    "Beta builds",
    "Whistler, Longhorn and other builds",
    "DOS systems and legacy boot images",
    "Linux installers and live systems",
    "Power",
    "Restart, shut down or enter firmware setup",
    "Utilities",
    "Diagnostics, recovery and firmware tools",
    "Install and repair Microsoft Windows",
    "Boot media preparation is complete.",
    "Starting EFI/BOOT from the prepared WORK partition...",
    "Starting chained bootloader",
    "Sun",
    "Mon",
    "Tue",
    "Wed",
    "Thu",
    "Fri",
    "Sat",
    "Delete partitions and install",
    "All current data on the selected disk will be lost.",
    "Formatting and the installer then start automatically.",
    "Confirm disk preparation",
    "Disk {0} - {1} MiB - GPT",
    "Disk {0} - {1} MiB - {2}, partitions: {3}",
    "New layout: one active {0} partition, {1}, drive letter C:",
    "Install MS-DOS on a disk",
    "Started from USB, C: is a RAM disk.",
    "Changes made in this session are lost when the computer is turned off.",
    "Start DOS and programs from USB",
    "Run programs from USB or install DOS on a disk",
    "No suitable target disk was found.",
    "Choose a disk for the new FAT16 partition. The USB drive is excluded.",
    "USOS will create a new FAT32 partition. The installation USB drive is excluded.",
    "RAM repair keeps the system and partitions. The USB drive is excluded.",
    "Apply the RAM fix",
    "Patcher9x / RAM fix",
    "The system and partitions stay. Changed files are backed up first.",
    "Repairs the installation in C:\\WINDOWS, also after the first restart.",
    "Windows 98 RAM repair",
    "The remaining space stays unallocated.",
    "Existing partitions on this disk will be deleted.",
    "Size of the new partition",
    "New Windows 98 SE installation",
    "Repair RAM support in an installed Windows 98",
    "Install Windows 98 or repair its support for more RAM",
    "Transferring control through UEFI LoadImage/StartImage...",
    "Starting EFI application",
    "USOS could not open the NTFS USOS_DATA volume.",
    "Images are read directly from DATA; ESP marker files are not used.",
    "DATA catalog unavailable",
    "EFI start failed",
    "This selection cannot start in the current firmware mode.",
    "Firmware mismatch",
    "Windows ISO start failed",
    "Preparation failed",
    "The operation stopped safely. Check the serial log if needed.",
    "The selected method has no working backend.",
    "Boot method unavailable",
    "XP preparation failed",
    "Loading Windows Boot Manager...",
    "Saving the one-shot handoff state...",
    "Windows installer preparation is complete.",
    "Please wait. The Windows logo will appear shortly.",
    "Loading the NTFS driver...",
    "Preparing the Windows Setup handoff...",
    "Starting Windows Setup",
    "Transferring control to Windows Setup...",
    "Verifying install.wim and EFI boot files...",
    "Locating the prepared WORK partition...",
    "Build {0}",
    "No mouse",
    "Boot menu",
    "Automatic - recommended",
    "USOS selects the supported boot path for this image automatically.",
    "For this Windows ISO it currently resolves to the ISO method below.",
    "Transfers control to another bootloader instead of preparing the image itself.",
    "Useful when the selected media already contains its own compatible bootloader.",
    "Chainload",
    "Treats an IMG file as a complete disk image rather than an optical image.",
    "Use it for utilities or systems distributed as raw disk images.",
    "Disk image",
    "Loads the selected EFI application directly through UEFI LoadImage/StartImage.",
    "Use it for standalone .efi boot programs that do not need another loader.",
    "EFI - direct UEFI start",
    "Treats an IMG file as a legacy floppy image.",
    "Intended for DOS-era boot disks and small legacy diagnostic tools.",
    "Floppy image",
    "USOS chooses the best implemented boot method for the selected image.",
    "Choose an explicit method only when you intentionally want to force that path.",
    "Extracts Windows Setup from the ISO to the WORK partition.",
    "After preparation USOS restarts once and boots Windows Setup from WORK.",
    "ISO - force ISO preparation",
    "Presents a small image as memory-backed boot media for legacy software.",
    "Primarily intended for DOS and older utilities, not modern Windows installers.",
    "Memdisk",
    "Copies installation files to the selected Windows partition.",
    "After preparation, remove the USB drive and start the computer from that disk.",
    "Automatic - Windows Setup",
    "Boots a prepared Windows installation stored in a VHD or VHDX image.",
    "It is for virtual-disk images, not normal Windows installation ISO files.",
    "VHDBoot",
    "Starts a Windows PE/WIM image using a WIM-oriented boot path.",
    "Useful when the source is a WIM instead of a complete installation ISO.",
    "WIMBoot",
    "Detects the installer version and starts it directly from ISO in UEFI.",
    "WinPE 7 receives UEFI compatibility and optional Drivers/x64 packages in RAM.",
    "Windows ISO - WIMBoot UEFI",
    "Windows Setup",
    "No supported image files were found in Images.",
    "Copy ISO, WIM, IMG, VHD, VHDX or EFI files into Images and try again.",
    "ISO, WIM, IMG, VHD, VHDX and EFI files are detected automatically",
    "Select image",
    "Shows mouse, touch and key events live. Press Esc twice to leave.",
    "Input test",
    "Reading optional Windows 7 x64 driver packages",
    "Starting external PE10; the install source remains the selected Windows ISO",
    "Starting the hybrid ISO's own WinPE and Setup",
    "Loading boot-source boot.wim: {0}%",
    "Reading the selected Windows ISO",
    "Validating installation ISO",
    "Loading Windows boot files",
    "Starting Windows Setup",
    "Starting Windows from ISO",
    "Validating the installation ISO and resolving the boot source",
    "Back",
    "Boot method",
    "Cancel",
    "Confirm",
    "Continue",
    "Diagnostics",
    "Next",
    "Open",
    "Power",
    "Power off",
    "Run",
    "Scroll",
    "Select",
    "Size",
    "Start",
    "Summary",
    "Use",
    "USOS menu",
    "English",
    "Choose what you want to boot or service",
    "What do you want to start?",
    "Automatic (Chainload)",
    "Automatic (DOS Setup)",
    "Automatic (EFI)",
    "Automatic (ISO)",
    "Automatic (MS-DOS / Windows 3.x)",
    "Automatic (SliTaz Live)",
    "Automatic (VHDBoot)",
    "Automatic (WIMBoot)",
    "Automatic (Windows 2000 Setup)",
    "Automatic (Windows Setup)",
    "Automatic (XP staging)",
    "Automatic (UEFI preparation / XP via CSM)",
    "Automatic",
    "Chainload",
    "Disk image",
    "Floppy image",
    "No boot methods are configured for this system.",
    "Choose how the selected image should be started",
    "Boot method",
    "No implemented boot backend supports this selection.",
    "This system stays visible because its backend is planned.",
    "No supported image files were found. Copy a file to:",
    "No images found",
    "APM power-off is unavailable on this computer.",
    "Turn off the computer manually.",
    "Firmware setup (BIOS/UEFI)",
    "Could not request firmware setup on the next restart.",
    "Firmware setup",
    "Not supported by this firmware",
    "Check the mouse, touchscreen and keys",
    "Restart",
    "Shut down",
    "Restart or shut down this computer",
    "Power",
    "Measured percentage, speed and time left appear during the file copy.",
    "USB / PARTUUID diagnostics - the screen is frozen for a photo",
    "[Diagnostics truncated - see the serial output]",
    "Starting environment",
    "Time left",
    "Ready - remove the USOS USB drive, then press Enter to power off.",
    "Do not disconnect the drive or turn off the computer.",
    "Preparation environment ready",
    "Next power-on: boot the target disk without USOS.",
    "Remove the USOS USB drive before powering off.",
    "Preparation request saved",
    "Return boot configured",
    "Speed",
    "Starting environment",
    "Verifying target device",
    "Preparing workspace",
    "Copying files",
    "Verification and finalization",
    "Starting preparation environment",
    "Done",
    "Failed",
    "In progress",
    "Waiting",
    "Step {0} of {1}",
    "Preparing Windows installer",
    "Starting XP disk selection",
    "Loading system images\xe2\x80\xa6",
    "Loading\xe2\x80\xa6",
    "Starting\xe2\x80\xa6",
    "Answer file",
    "Boot PE",
    "Boot source ISO",
    "Disk",
    "Driver inventory",
    "External drivers",
    "Error",
    "Image",
    "INF files: {0}; Windows checks the hardware match",
    "ISO case",
    "ISO inspection",
    "Method",
    "None in Drivers/x64; target USB 3 may be unavailable",
    "Preparation",
    "Source",
    "Review the selected boot configuration",
    "System",
    "Target support",
    "Ready to start",
    "Unavailable",
    "USB",
    "Vista SP2 x64 -> PE10; the target needs CSM enabled",
    "KB2864202 + signed USB package + pre-Setup v11",
    "PE10 native USB; the target uses Vista USB v11",
    "Selected and confirmed in the next graphical screen",
    "Custom unattended files are not supported on this XP UEFI path.",
    "UEFI; installed XP requires firmware CSM and MBR",
    "XP SP3 x86; ACPI / SATA / USB drivers; optional PAE boot entry",
    "Copy images to {0}",
    "Images: {0}",
    "No image",
    "Ready",
    "Requires BIOS",
    "This system starts only in BIOS mode; USOS is running in UEFI mode.",
    "Requires UEFI",
    "This system starts only in UEFI mode; USOS is running in BIOS mode.",
    "Unavailable",
    "No working boot backend supports this system yet.",
    "Select a system, distribution or utility group",
    "The selected answer file is copied after the target safety check.",
    "No answer file",
    "Use the default setup options without a custom answer file.",
    "Choose an answer file or continue without one",
    "Unattended setup",
    "DOS programs from USB, file manager and command prompt",
    "Built-in: CPU, RAM, motherboard and disks",
    "No utility folders were found on this USOS drive.",
    "Create Utilities/<tool name>/Images on DATA, then run Update USOS.",
    "No utilities",
    "This utility stays visible while its boot backend is unavailable.",
    "Please wait",
    "Please wait - keep the USB drive connected",
};
