// Generated by installer/cmd/usos-i18n-gen from installer/internal/i18n/locales. Do not edit.
// English is built in; lang.bin on the ESP carries only the chosen language.

pub const Key = enum(u16) {
    badge_experimental,
    badge_ready,
    badge_recommended,
    badge_tested_in_vm,
    badge_unavailable,
    bios_backend_failed_line1,
    bios_backend_failed_title,
    bios_hardware,
    bios_loading,
    bios_loading_files,
    bios_no_images_title,
    bios_setup_help,
    bios_setup_progress,
    bios_setup_reading,
    bios_setup_title,
    bios_setup_failed_line1,
    bios_setup_failed_line2,
    bios_setup_failed_line3,
    bios_setup_failed_title,
    bios_starting_installer,
    bios_xp_resume_continue,
    bios_xp_resume_line1,
    bios_xp_resume_line2,
    bios_xp_resume_line3,
    bios_xp_resume_line4,
    bios_xp_resume_title,
    category_beta,
    category_beta_desc,
    category_dos_desc,
    category_linux_desc,
    category_power,
    category_power_desc,
    category_utilities,
    category_utilities_desc,
    category_windows_desc,
    day_0,
    day_1,
    day_2,
    day_3,
    day_4,
    day_5,
    day_6,
    donor_corrupt,
    donor_missing,
    dos_confirm_go,
    dos_confirm_note1,
    dos_confirm_note2,
    dos_confirm_title,
    dos_disk,
    dos_disk_mbr,
    dos_layout,
    dos_msdos_install,
    dos_msdos_note1,
    dos_msdos_note2,
    dos_msdos_run,
    dos_msdos_subtitle,
    dos_no_disks,
    dos_pick_fat16,
    dos_pick_fat32,
    dos_pick_repair,
    dos_repair_apply,
    dos_repair_detail,
    dos_repair_note1,
    dos_repair_note2,
    dos_repair_title,
    dos_size_note1,
    dos_size_note2,
    dos_size_title,
    dos_w98_install,
    dos_w98_repair,
    dos_w98_subtitle,
    drivers_blocked,
    drivers_blocked_note,
    drivers_builtin,
    drivers_desc,
    drivers_file,
    drivers_how,
    drivers_match_everywhere,
    drivers_match_no,
    drivers_match_yes,
    drivers_next_boot,
    drivers_none,
    drivers_ntfs_detail,
    drivers_ntfs_line1,
    drivers_ntfs_line2,
    drivers_off,
    drivers_on,
    drivers_sb_off,
    drivers_sb_signed,
    drivers_sb_verified,
    drivers_state_blocked,
    drivers_state_duplicate,
    drivers_state_failed,
    drivers_state_failed_short,
    drivers_state_file,
    drivers_state_not_matched,
    drivers_state_off,
    drivers_state_refused,
    drivers_state_signature,
    drivers_state_started,
    drivers_title,
    drivers_toggle_hint,
    drivers_toggle_unusable,
    drivers_touch_match,
    drivers_type,
    header_build,
    header_subtitle,
    help_auto_title,
    help_auto_iso_line1,
    help_auto_iso_line2,
    help_chainload_line1,
    help_chainload_line2,
    help_chainload_title,
    help_disk_image_line1,
    help_disk_image_line2,
    help_disk_image_title,
    help_efi_line1,
    help_efi_line2,
    help_efi_title,
    help_floppy_line1,
    help_floppy_line2,
    help_floppy_title,
    help_generic_line1,
    help_generic_line2,
    help_iso_line1,
    help_iso_line2,
    help_iso_title,
    help_memdisk_line1,
    help_memdisk_line2,
    help_memdisk_title,
    help_setup_line1,
    help_setup_line2,
    help_setup_title,
    help_vhdboot_line1,
    help_vhdboot_line2,
    help_vhdboot_title,
    help_wimboot_line1,
    help_wimboot_line2,
    help_wimboot_title,
    help_win10_wimboot_line1,
    help_win10_wimboot_line2,
    help_windows_setup_title,
    images_none_line1,
    images_none_line2,
    images_subtitle,
    images_title,
    input_test_help,
    input_test_title,
    key_back,
    key_boot_method,
    key_cancel,
    key_confirm,
    key_continue,
    key_diagnostics,
    key_next,
    key_open,
    key_power,
    key_power_off,
    key_run,
    key_scroll,
    key_select,
    key_size,
    key_start,
    key_summary,
    key_use,
    key_usos_menu,
    language_name,
    linux_unverified,
    media_blocked_32bit,
    media_blocked_arm64,
    media_blocked_line2,
    media_blocked_no_uefi,
    media_blocked_title,
    media_not_windows,
    media_setup,
    media_unreadable,
    media_winpe,
    media_winpe_badge,
    media_winpe_line1,
    media_winpe_line2,
    menu_subtitle,
    menu_title,
    method_auto_chainload,
    method_auto_dos_setup,
    method_auto_efi,
    method_auto_iso,
    method_auto_msdos,
    method_auto_slitaz,
    method_auto_vhdboot,
    method_auto_wimboot,
    method_auto_win2000,
    method_auto_windows_setup,
    method_auto_xp,
    method_auto_xp_uefi,
    method_automatic,
    method_chainload,
    method_disk_image,
    method_floppy_image,
    methods_none,
    methods_subtitle,
    methods_title,
    notice_no_image_line1,
    notice_no_image_title,
    power_apm_line1,
    power_apm_line2,
    power_input_test,
    power_restart,
    power_shutdown,
    power_subtitle,
    power_title,
    prep_copy_note,
    prep_diag_title,
    prep_diag_truncated,
    prep_env_title,
    prep_eta,
    prep_footer_done,
    prep_footer_running,
    prep_next_boot,
    prep_remove_usb,
    prep_speed,
    prep_stage_1,
    prep_stage_2,
    prep_stage_3,
    prep_stage_4,
    prep_stage_5,
    prep_status_done,
    prep_status_failed,
    prep_status_running,
    prep_status_waiting,
    prep_step,
    prep_title,
    sbinfo_absent,
    sbinfo_add_needs_off,
    sbinfo_add_needs_shim,
    sbinfo_desc,
    sbinfo_guide_csm,
    sbinfo_guide_default_keys,
    sbinfo_guide_first,
    sbinfo_guide_ms_ca,
    sbinfo_how,
    sbinfo_how_line1,
    sbinfo_how_line2,
    sbinfo_how_line3,
    sbinfo_how_line4,
    sbinfo_key_denied,
    sbinfo_key_missing,
    sbinfo_key_saved,
    sbinfo_key_short_missing,
    sbinfo_key_short_saved,
    sbinfo_key_unknown,
    sbinfo_no_cert,
    sbinfo_off,
    sbinfo_on,
    sbinfo_pk_no,
    sbinfo_pk_yes,
    sbinfo_present,
    sbinfo_remind,
    sbinfo_remove_hint,
    sbinfo_sb_off,
    sbinfo_sb_on,
    sbinfo_sb_setup,
    sbinfo_sb_unsupported,
    sbinfo_title,
    sbkey_add,
    sbkey_back_menu,
    sbkey_banner,
    sbkey_banner_action,
    sbkey_confirm_line1,
    sbkey_confirm_line2,
    sbkey_confirm_title,
    sbkey_failed_line1,
    sbkey_failed_title,
    sbkey_never,
    sbkey_never_note,
    sbkey_no,
    sbkey_not_now,
    sbkey_offer_line1,
    sbkey_offer_line2,
    sbkey_open_setup,
    sbkey_saved_line1,
    sbkey_saved_title,
    sbkey_title,
    sbkey_yes,
    system_copy_to,
    system_image_count,
    system_no_image,
    system_ready,
    system_requires_bios,
    system_requires_bios_detail,
    system_requires_bios_hint,
    system_requires_uefi,
    system_requires_uefi_detail,
    system_requires_uefi_hint,
    system_unavailable,
    system_unavailable_detail,
    systems_subtitle,
    themes_builtin,
    themes_current,
    themes_desc,
    themes_hint,
    themes_invalid,
    themes_name_dark,
    themes_name_default,
    themes_name_high_contrast,
    themes_name_light,
    themes_name_retro,
    themes_title,
    themes_user,
    unattended_file_detail,
    unattended_none,
    unattended_none_detail,
    unattended_subtitle,
    unattended_title,
    unattended_vista_uefi,
    unattended_vista_uefi_detail,
    unattended_xp_file_detail,
    unattended_xp_manual,
    unattended_xp_manual_detail,
    unattended_xp_settings,
    unattended_xp_settings_detail,
    utilities_freedos_desc,
    utilities_hardware_desc,
    utilities_none_line1,
    utilities_none_line2,
    utilities_none_title,
    wait,
    wait_usb,
    action_blocked,
    action_chainload,
    action_efi,
    action_hint,
    action_iso,
    action_linux,
    action_vhdboot,
    action_wimboot,
    action_winpe,
    action_xp,
    chainload_line1,
    chainload_line2,
    chainload_title,
    efi_line1,
    efi_title,
    error_catalog_line1,
    error_catalog_line2,
    error_catalog_title,
    error_efi,
    error_firmware_line1,
    error_firmware_title,
    error_iso,
    error_linux,
    error_linux_fragmented,
    error_linux_helper,
    error_linux_no_entry,
    error_preparation,
    error_secure_boot_rejected,
    error_stopped,
    error_unsupported_line1,
    error_unsupported_title,
    error_xp,
    form_empty,
    form_key_backspace,
    form_key_change,
    form_key_type,
    form_off,
    form_on,
    form_osk_done,
    form_osk_shift,
    form_osk_space,
    form_picker_subtitle,
    handoff_bootmgr,
    handoff_commit,
    handoff_line1,
    handoff_line2,
    handoff_ntfs,
    handoff_setup,
    handoff_title,
    handoff_transfer,
    handoff_verify,
    handoff_work,
    header_no_mouse,
    help_win7_wimboot_line1,
    help_win7_wimboot_line2,
    help_win7_wimboot_title,
    iso_drivers,
    iso_external_pe,
    iso_hybrid_pe,
    iso_loading_wim,
    iso_reading,
    iso_stage_1,
    iso_stage_2,
    iso_stage_3,
    iso_title,
    iso_validating,
    notice_backend_line1,
    notice_backend_line2,
    power_firmware,
    power_firmware_error_line1,
    power_firmware_error_title,
    power_firmware_unsupported,
    prep_loader_ready,
    prep_request_saved,
    prep_return_boot,
    prep_starting,
    prep_xp_disks,
    profile_add,
    profile_add_detail,
    profile_add_detail_linux,
    profile_arch_warning,
    profile_badge,
    profile_badge_incomplete,
    profile_cancel,
    profile_delete_confirm,
    profile_delete_keep,
    profile_delete_question,
    profile_delete_title,
    profile_edition_missing,
    profile_editor_new,
    profile_editor_subtitle,
    profile_editor_subtitle_linux,
    profile_editor_title,
    profile_field_bypass_ram,
    profile_field_bypass_secure_boot,
    profile_field_bypass_tpm,
    profile_field_classic_start,
    profile_field_computer,
    profile_field_disable_uac,
    profile_field_disable_wer,
    profile_field_display,
    profile_field_edition,
    profile_field_hide_outlook_express,
    profile_field_key,
    profile_field_keyboard,
    profile_field_language,
    profile_field_local_account,
    profile_field_locale,
    profile_field_name,
    profile_field_network_location,
    profile_field_no_autorun,
    profile_field_no_balloon_tips,
    profile_field_no_hibernation,
    profile_field_no_network,
    profile_field_no_sidebar,
    profile_field_no_welcome_center,
    profile_field_org,
    profile_field_password,
    profile_field_protect_pc,
    profile_field_remember_key,
    profile_field_show_extensions,
    profile_field_show_hidden,
    profile_field_skip_games,
    profile_field_skip_msn,
    profile_field_systems,
    profile_field_theme,
    profile_field_timezone,
    profile_field_user,
    profile_field_user2,
    profile_file_detail,
    profile_help_bypass,
    profile_help_classic_start,
    profile_help_computer,
    profile_help_disable_uac,
    profile_help_disable_wer,
    profile_help_display,
    profile_help_edition,
    profile_help_hide_outlook_express,
    profile_help_key,
    profile_help_keyboard,
    profile_help_language,
    profile_help_local_account,
    profile_help_locale,
    profile_help_name,
    profile_help_network_location,
    profile_help_no_autorun,
    profile_help_no_balloon_tips,
    profile_help_no_hibernation,
    profile_help_no_network,
    profile_help_no_sidebar,
    profile_help_no_welcome_center,
    profile_help_org,
    profile_help_password,
    profile_help_protect_pc,
    profile_help_remember_key,
    profile_help_show_extensions,
    profile_help_show_hidden,
    profile_help_skip_games,
    profile_help_skip_msn,
    profile_help_systems,
    profile_help_theme,
    profile_help_timezone,
    profile_help_user,
    profile_help_user2,
    profile_key_delete,
    profile_key_edit,
    profile_key_import,
    profile_key_use,
    profile_manual_detail,
    profile_missing_key,
    profile_missing_password,
    profile_problem_bad_characters,
    profile_problem_bad_key_format,
    profile_problem_duplicate,
    profile_problem_empty,
    profile_problem_only_digits,
    profile_problem_reserved_name,
    profile_problem_same_as_user,
    profile_problem_too_long,
    profile_row_detail,
    profile_row_help,
    profile_save,
    profile_save_failed,
    profile_section_extras,
    profile_summary,
    profile_value_auto,
    profile_value_edition_manual,
    profile_value_network_home,
    profile_value_network_public,
    profile_value_network_work,
    profile_value_protect_off,
    profile_value_protect_recommended,
    profile_value_protect_updates,
    profile_value_same_language,
    profile_value_same_locale,
    profile_value_setup_asks,
    profile_value_systems_all,
    profile_value_systems_linux,
    profile_value_systems_only,
    profile_value_systems_windows,
    profile_value_theme_basic,
    profile_value_theme_classic,
    profile_value_theme_default,
    profile_xp_ini_detail,
    server_belongs_in,
    server_blocked_ia64,
    server_client_in_server_folder,
    server_core,
    server_desktop,
    server_editions,
    server_in_client_folder,
    server_nvme_hint,
    server_section,
    server_section_detail,
    server_setup,
    splash_images,
    splash_loading,
    splash_starting,
    summary_answer_file,
    summary_boot_pe,
    summary_boot_source,
    summary_disk,
    summary_driver_inventory,
    summary_drivers,
    summary_edition,
    summary_edition_value,
    summary_error,
    summary_esp_guard,
    summary_esp_guard_label,
    summary_image,
    summary_inf_count,
    summary_iso_case,
    summary_iso_inspection,
    summary_method,
    summary_native_case,
    summary_no_answer_files,
    summary_no_drivers,
    summary_nt52_limits,
    summary_preparation,
    summary_secure_boot_badge,
    summary_secure_boot_detail,
    summary_secure_boot_line1,
    summary_secure_boot_line2,
    summary_secure_boot_linux_line1,
    summary_secure_boot_title,
    summary_source,
    summary_subtitle,
    summary_system,
    summary_target_support,
    summary_title,
    summary_unavailable,
    summary_usb,
    summary_user_drivers,
    summary_user_drivers_count,
    summary_user_drivers_folder,
    summary_vista_case,
    summary_vista_case_nocsm,
    summary_vista_csmwrap,
    summary_vista_support,
    summary_vista_usb,
    summary_w2k_limits,
    summary_xp_csmwrap,
    summary_xp_disk,
    summary_xp_preparation,
    summary_xp_sif_merged,
    summary_xp_source,
    theme_edit_blocked,
    theme_edit_cancel,
    theme_edit_contrast_bad,
    theme_edit_contrast_ok,
    theme_edit_element_accent,
    theme_edit_element_accent_pressed,
    theme_edit_element_accent_soft,
    theme_edit_element_background,
    theme_edit_element_border,
    theme_edit_element_border_strong,
    theme_edit_element_danger,
    theme_edit_element_danger_soft,
    theme_edit_element_disabled,
    theme_edit_element_disabled_text,
    theme_edit_element_faint,
    theme_edit_element_field,
    theme_edit_element_header,
    theme_edit_element_muted,
    theme_edit_element_on_accent,
    theme_edit_element_on_pad,
    theme_edit_element_pad_x,
    theme_edit_element_panel,
    theme_edit_element_panel_alt,
    theme_edit_element_selected,
    theme_edit_element_success,
    theme_edit_element_success_soft,
    theme_edit_element_text,
    theme_edit_element_warning,
    theme_edit_element_warning_soft,
    theme_edit_field_base,
    theme_edit_field_blue,
    theme_edit_field_color,
    theme_edit_field_element,
    theme_edit_field_green,
    theme_edit_field_name,
    theme_edit_field_red,
    theme_edit_help_base,
    theme_edit_help_channel,
    theme_edit_help_color,
    theme_edit_help_element,
    theme_edit_help_name,
    theme_edit_open,
    theme_edit_open_detail,
    theme_edit_pair,
    theme_edit_preview_button,
    theme_edit_preview_disabled,
    theme_edit_preview_row,
    theme_edit_preview_text,
    theme_edit_preview_title,
    theme_edit_reset,
    theme_edit_save,
    theme_edit_save_failed,
    theme_edit_saved,
    theme_edit_subtitle,
    theme_edit_title,
    utilities_shell_desc,
    utilities_shell_title,
    utility_unavailable,
    xp_prep_checking,
    xp_prep_choose_disk,
    xp_prep_copy_verify,
    xp_prep_environment,
    xp_prep_loading,
    xp_prep_starting,
};

/// FNV-1a 32 of the key names stored in lang.bin (without the "boot." prefix).
pub const hashes = [_]u32{
    0xe81a21c0, // badge.experimental
    0x70416b89, // badge.ready
    0xc1e902c9, // badge.recommended
    0xa07f0359, // badge.tested_in_vm
    0xf502a3ec, // badge.unavailable
    0x1dc0f3e7, // bios.backend_failed.line1
    0x175fbc90, // bios.backend_failed.title
    0xfbb764e0, // bios.hardware
    0x41fa93a4, // bios.loading
    0x993dc1bc, // bios.loading_files
    0x7724e692, // bios.no_images.title
    0xffdc61f6, // bios.setup.help
    0xd454f13a, // bios.setup.progress
    0xb086080f, // bios.setup.reading
    0xe960c5dd, // bios.setup.title
    0xd6ba7a18, // bios.setup_failed.line1
    0xd9ba7ed1, // bios.setup_failed.line2
    0xd8ba7d3e, // bios.setup_failed.line3
    0xfa32ec43, // bios.setup_failed.title
    0x7ea092f3, // bios.starting_installer
    0x1f902dd5, // bios.xp_resume.continue
    0x3eb756f5, // bios.xp_resume.line1
    0x3bb7523c, // bios.xp_resume.line2
    0x3cb753cf, // bios.xp_resume.line3
    0x39b74f16, // bios.xp_resume.line4
    0xce8a7b02, // bios.xp_resume.title
    0xdfc5a04f, // category.beta
    0x50adb2ee, // category.beta.desc
    0xc4dcd124, // category.dos.desc
    0xf91b310c, // category.linux.desc
    0x47a1786e, // category.power
    0x3595e4b1, // category.power.desc
    0x0443aa4f, // category.utilities
    0x977550ee, // category.utilities.desc
    0xb473adb5, // category.windows.desc
    0xe039545b, // day.0
    0xdf3952c8, // day.1
    0xe2395781, // day.2
    0xe13955ee, // day.3
    0xe4395aa7, // day.4
    0xe3395914, // day.5
    0xe6395dcd, // day.6
    0x0b01efb8, // donor.corrupt
    0xa7ab84a5, // donor.missing
    0xebddf16d, // dos.confirm.go
    0x44551082, // dos.confirm.note1
    0x43550eef, // dos.confirm.note2
    0x8aa8f83f, // dos.confirm.title
    0x6081ba68, // dos.disk
    0xf3336024, // dos.disk_mbr
    0x5987730b, // dos.layout
    0x6ca16ba4, // dos.msdos.install
    0xc71281a8, // dos.msdos.note1
    0xca128661, // dos.msdos.note2
    0x8c98b19e, // dos.msdos.run
    0x84ecd0dd, // dos.msdos.subtitle
    0xb5cfa773, // dos.no_disks
    0x1cf46ed6, // dos.pick.fat16
    0xa8f9c868, // dos.pick.fat32
    0x095414a3, // dos.pick.repair
    0x636cf32a, // dos.repair.apply
    0xc5fe23b3, // dos.repair.detail
    0x68d075cd, // dos.repair.note1
    0x65d07114, // dos.repair.note2
    0xfbdbe764, // dos.repair.title
    0x32bc1fa5, // dos.size.note1
    0x2fbc1aec, // dos.size.note2
    0xfdb391bc, // dos.size.title
    0x98538446, // dos.w98.install
    0xaaa58af6, // dos.w98.repair
    0xca53fd63, // dos.w98.subtitle
    0xbc36c95a, // drivers.blocked
    0xe82a5e8f, // drivers.blocked_note
    0xf3277059, // drivers.builtin
    0xcbe8b9df, // drivers.desc
    0xe7475358, // drivers.file
    0x07f137a0, // drivers.how
    0x7e4e9a62, // drivers.match_everywhere
    0x2cf8ba17, // drivers.match_no
    0x36b0e503, // drivers.match_yes
    0x8b6cf084, // drivers.next_boot
    0xca908354, // drivers.none
    0xf2437359, // drivers.ntfs_detail
    0xc194d5e9, // drivers.ntfs_line1
    0xbe94d130, // drivers.ntfs_line2
    0x07bae9fb, // drivers.off
    0xe8466337, // drivers.on
    0xf5bb2515, // drivers.sb_off
    0x716e4878, // drivers.sb_signed
    0x5429d6a4, // drivers.sb_verified
    0x74e76674, // drivers.state_blocked
    0xa47eebd5, // drivers.state_duplicate
    0xfc581309, // drivers.state_failed
    0x1640b004, // drivers.state_failed_short
    0x90f65b82, // drivers.state_file
    0x5daaa246, // drivers.state_not_matched
    0xb2021279, // drivers.state_off
    0x18f3cbec, // drivers.state_refused
    0x893e000e, // drivers.state_signature
    0xcc5857d9, // drivers.state_started
    0x1e4853f8, // drivers.title
    0x4280a47a, // drivers.toggle_hint
    0x8033a4b0, // drivers.toggle_unusable
    0x2e0de3cb, // drivers.touch_match
    0x28c59d9e, // drivers.type
    0x9d2e5b72, // header.build
    0xf19fe29e, // header.subtitle
    0xf6a9e837, // help.auto.title
    0x5353cd3a, // help.auto_iso.line1
    0x5253cba7, // help.auto_iso.line2
    0xc18f8922, // help.chainload.line1
    0xc08f878f, // help.chainload.line2
    0xb6117989, // help.chainload.title
    0x1e171c68, // help.disk_image.line1
    0x21172121, // help.disk_image.line2
    0x5dbfe7f3, // help.disk_image.title
    0x6d5238ed, // help.efi.line1
    0x6a523434, // help.efi.line2
    0xf06fc68a, // help.efi.title
    0x7e1ee4d1, // help.floppy.line1
    0x7b1ee018, // help.floppy.line2
    0x4ca057b6, // help.floppy.title
    0x65002e6a, // help.generic.line1
    0x64002cd7, // help.generic.line2
    0xb898037a, // help.iso.line1
    0xb79801e7, // help.iso.line2
    0x8a0ebf31, // help.iso.title
    0x10d398e7, // help.memdisk.line1
    0x11d39a7a, // help.memdisk.line2
    0x0a726190, // help.memdisk.title
    0x0f150192, // help.setup.line1
    0x0e14ffff, // help.setup.line2
    0x5290dd59, // help.setup.title
    0xbb1cf439, // help.vhdboot.line1
    0xb81cef80, // help.vhdboot.line2
    0x1c220d4e, // help.vhdboot.title
    0x1b96152c, // help.wimboot.line1
    0x1e9619e5, // help.wimboot.line2
    0x212fbc8f, // help.wimboot.title
    0xf5a59c4c, // help.win10_wimboot.line1
    0xf8a5a105, // help.win10_wimboot.line2
    0x18900e83, // help.windows_setup.title
    0xa083adfa, // images.none.line1
    0x9f83ac67, // images.none.line2
    0x7192a123, // images.subtitle
    0x403d0617, // images.title
    0x3f42c8f5, // input_test.help
    0xeccf9134, // input_test.title
    0x5bf90715, // key.back
    0x1282304e, // key.boot_method
    0xeee5a29c, // key.cancel
    0x70bcc806, // key.confirm
    0x6528007f, // key.continue
    0x7b94114e, // key.diagnostics
    0x5ee1de9b, // key.next
    0x7516d1e6, // key.open
    0x5c531bb7, // key.power
    0x983f3e9d, // key.power_off
    0x3210481f, // key.run
    0xa9502577, // key.scroll
    0xd858a6be, // key.select
    0xee6c2be7, // key.size
    0xc4db73e6, // key.start
    0x01545ee2, // key.summary
    0xce8206d1, // key.use
    0xaf281282, // key.usos_menu
    0x5aa9bbcc, // language.name
    0x30be067e, // linux.unverified
    0x72a0bdee, // media.blocked_32bit
    0x30d9d376, // media.blocked_arm64
    0x655e4fe6, // media.blocked_line2
    0x51f33129, // media.blocked_no_uefi
    0x98318504, // media.blocked_title
    0x3c08652a, // media.not_windows
    0xece75d88, // media.setup
    0xca296b94, // media.unreadable
    0x78234508, // media.winpe
    0x9742b308, // media.winpe_badge
    0xb982b1d2, // media.winpe_line1
    0xb882b03f, // media.winpe_line2
    0x041dd1a8, // menu.subtitle
    0x82ff555a, // menu.title
    0x9166eacb, // method.auto_chainload
    0xac512b2e, // method.auto_dos_setup
    0xcf4f3104, // method.auto_efi
    0x3b5c2e47, // method.auto_iso
    0xdf251230, // method.auto_msdos
    0xdc54235f, // method.auto_slitaz
    0xd0d5afbc, // method.auto_vhdboot
    0xaaec70e9, // method.auto_wimboot
    0x1fcc2a9a, // method.auto_win2000
    0xabbaa3a1, // method.auto_windows_setup
    0x4c33f486, // method.auto_xp
    0x34663e98, // method.auto_xp_uefi
    0x693c9e3d, // method.automatic
    0x92d38fcf, // method.chainload
    0xa9de181d, // method.disk_image
    0x95f4de1e, // method.floppy_image
    0x9593c94b, // methods.none
    0x88241669, // methods.subtitle
    0x616e0619, // methods.title
    0xe2e6f917, // notice.no_image.line1
    0x2b57a9a0, // notice.no_image.title
    0x4542418f, // power.apm.line1
    0x46424322, // power.apm.line2
    0x94bdee21, // power.input_test
    0x77e5c8b3, // power.restart
    0x61976512, // power.shutdown
    0x267882fc, // power.subtitle
    0xe7aba2de, // power.title
    0x14cb484e, // prep.copy_note
    0x91b207e7, // prep.diag.title
    0x051fa553, // prep.diag.truncated
    0x0623d95f, // prep.env.title
    0xec0a0b0c, // prep.eta
    0xfa71f86f, // prep.footer.done
    0x6c030272, // prep.footer.running
    0x848caac2, // prep.next_boot
    0xc7e6fd7d, // prep.remove_usb
    0x6f11970f, // prep.speed
    0x7e12c69f, // prep.stage.1
    0x7f12c832, // prep.stage.2
    0x8012c9c5, // prep.stage.3
    0x7912bec0, // prep.stage.4
    0x7a12c053, // prep.stage.5
    0x96053b70, // prep.status.done
    0x739921d5, // prep.status.failed
    0x0773ae1f, // prep.status.running
    0x5de2d29f, // prep.status.waiting
    0x5a2661f6, // prep.step
    0x84ce2712, // prep.title
    0x0d899acf, // sbinfo.absent
    0x9e2530dd, // sbinfo.add_needs_off
    0xf5aa9821, // sbinfo.add_needs_shim
    0x491358b7, // sbinfo.desc
    0x02c5df3c, // sbinfo.guide_csm
    0xffe47e61, // sbinfo.guide_default_keys
    0x1ce51827, // sbinfo.guide_first
    0x51e10d64, // sbinfo.guide_ms_ca
    0x74355308, // sbinfo.how
    0xf8944fd2, // sbinfo.how_line1
    0xf7944e3f, // sbinfo.how_line2
    0xf6944cac, // sbinfo.how_line3
    0xf5944b19, // sbinfo.how_line4
    0x7e82a855, // sbinfo.key_denied
    0xf388d60a, // sbinfo.key_missing
    0x91c57175, // sbinfo.key_saved
    0x03b334ff, // sbinfo.key_short_missing
    0x99146cbc, // sbinfo.key_short_saved
    0x7a3d527c, // sbinfo.key_unknown
    0x9d0b5e08, // sbinfo.no_cert
    0x3425b013, // sbinfo.off
    0xc82a9b4f, // sbinfo.on
    0x5bbf17eb, // sbinfo.pk_no
    0x237c6f57, // sbinfo.pk_yes
    0x1f8e41a9, // sbinfo.present
    0xb8be361b, // sbinfo.remind
    0x96476e16, // sbinfo.remove_hint
    0xcc03016d, // sbinfo.sb_off
    0xc99edd31, // sbinfo.sb_on
    0x718f9815, // sbinfo.sb_setup
    0x88fb8557, // sbinfo.sb_unsupported
    0xf386e6a0, // sbinfo.title
    0x97fca9c6, // sbkey.add
    0xd00e547e, // sbkey.back_menu
    0x8ae86fc5, // sbkey.banner
    0x13784be4, // sbkey.banner_action
    0xf3f648cf, // sbkey.confirm_line1
    0xf4f64a62, // sbkey.confirm_line2
    0x84200708, // sbkey.confirm_title
    0xd24c51b8, // sbkey.failed_line1
    0x734b2463, // sbkey.failed_title
    0x39f3e177, // sbkey.never
    0xe43bbd14, // sbkey.never_note
    0xbcd77668, // sbkey.no
    0xd6be6c03, // sbkey.not_now
    0xf71ed549, // sbkey.offer_line1
    0xf41ed090, // sbkey.offer_line2
    0x18485ded, // sbkey.open_setup
    0x415d50a8, // sbkey.saved_line1
    0xee1489b3, // sbkey.saved_title
    0xff5020b3, // sbkey.title
    0xd9dbe826, // sbkey.yes
    0x6fd0eb35, // system.copy_to
    0x4961b793, // system.image_count
    0x2a578ca3, // system.no_image
    0xd3048155, // system.ready
    0xab6c36c8, // system.requires_bios
    0x47e54d83, // system.requires_bios.detail
    0xb33e3eff, // system.requires_bios.hint
    0xeb00f308, // system.requires_uefi
    0xc483f543, // system.requires_uefi.detail
    0xa4c837bf, // system.requires_uefi.hint
    0x31aec0c8, // system.unavailable
    0xa6ba9b83, // system.unavailable.detail
    0xab5ff4f5, // systems.subtitle
    0xf0db4556, // themes.builtin
    0xaef5a0d8, // themes.current
    0x68214e12, // themes.desc
    0x4f5530c6, // themes.hint
    0x43c727ce, // themes.invalid
    0x02a08382, // themes.name.dark
    0x94b57963, // themes.name.default
    0xa784564d, // themes.name.high_contrast
    0x991efc02, // themes.name.light
    0x1fe4168e, // themes.name.retro
    0x8246578f, // themes.title
    0xb4b7e3f4, // themes.user
    0x42cdb840, // unattended.file.detail
    0x9b91564d, // unattended.none
    0x16e5e868, // unattended.none.detail
    0x0404a4d7, // unattended.subtitle
    0x117edf4b, // unattended.title
    0x318ddc7a, // unattended.vista_uefi
    0xb090eb5e, // unattended.vista_uefi_detail
    0xc77e920d, // unattended.xp_file.detail
    0xd75cdb9a, // unattended.xp_manual
    0x922274cd, // unattended.xp_manual.detail
    0x33bff8f1, // unattended.xp_settings
    0x8b01f4fc, // unattended.xp_settings.detail
    0x90427850, // utilities.freedos.desc
    0xbe35b4e2, // utilities.hardware.desc
    0x89ec8a66, // utilities.none.line1
    0x88ec88d3, // utilities.none.line2
    0x638b0125, // utilities.none.title
    0x892e4ca0, // wait
    0x3e1f8ab9, // wait_usb
    0xb9a53ded, // action.blocked
    0x67542164, // action.chainload
    0x4743492f, // action.efi
    0x8d1362d2, // action.hint
    0xf7710f28, // action.iso
    0x972002f3, // action.linux
    0x351f129f, // action.vhdboot
    0x3979b582, // action.wimboot
    0xb3fd0db4, // action.winpe
    0x45058703, // action.xp
    0xfc4d4ef9, // chainload.line1
    0xf94d4a40, // chainload.line2
    0xb38e898e, // chainload.title
    0x23541dfa, // efi.line1
    0xf4cad9b1, // efi.title
    0x35820aab, // error.catalog.line1
    0x36820c3e, // error.catalog.line2
    0x9807296c, // error.catalog.title
    0x31ce0c49, // error.efi
    0x1ec31a4f, // error.firmware.line1
    0xaeecd888, // error.firmware.title
    0x5f16a066, // error.iso
    0x71170d15, // error.linux
    0x4cffd5cf, // error.linux_fragmented
    0xb3a23c5a, // error.linux_helper
    0x5f65566e, // error.linux_no_entry
    0xacc67c62, // error.preparation
    0x18cdd544, // error.secure_boot_rejected
    0xfe82b516, // error.stopped
    0x96c6d0e3, // error.unsupported.line1
    0x471635f4, // error.unsupported.title
    0x74a11b6d, // error.xp
    0xd2e92c28, // form.empty
    0x068d58eb, // form.key.backspace
    0x4f03dbc4, // form.key.change
    0x33e2e09c, // form.key.type
    0xae287c48, // form.off
    0xcf665366, // form.on
    0xafc445f4, // form.osk.done
    0x97415b00, // form.osk.shift
    0xccbac9aa, // form.osk.space
    0x06577659, // form.picker.subtitle
    0x096158f9, // handoff.bootmgr
    0x12a81bf8, // handoff.commit
    0x23c3a3ee, // handoff.line1
    0x22c3a25b, // handoff.line2
    0x1020d73c, // handoff.ntfs
    0x715fcb22, // handoff.setup
    0x8496255d, // handoff.title
    0x40ae76c2, // handoff.transfer
    0x467b2d38, // handoff.verify
    0x3359246c, // handoff.work
    0x2b0a3151, // header.no_mouse
    0x4bf3a4b0, // help.win7_wimboot.line1
    0x4ef3a969, // help.win7_wimboot.line2
    0xc579f0eb, // help.win7_wimboot.title
    0x646697d7, // iso.drivers
    0x2482ded7, // iso.external_pe
    0x244161e4, // iso.hybrid_pe
    0x9f2ad69c, // iso.loading_wim
    0xac900584, // iso.reading
    0xd364e7f3, // iso.stage.1
    0xd464e986, // iso.stage.2
    0xd564eb19, // iso.stage.3
    0x1fdc1e96, // iso.title
    0xd22ab261, // iso.validating
    0x48a2a970, // notice.backend.line1
    0x4ba2ae29, // notice.backend.line2
    0x69b9a301, // power.firmware
    0x8aa47bc2, // power.firmware.error.line1
    0xe35e84a9, // power.firmware.error.title
    0x80093ad8, // power.firmware.unsupported
    0x48d1e0f7, // prep.loader_ready
    0xce2deea5, // prep.request_saved
    0x6a7e2473, // prep.return_boot
    0x416d9ce0, // prep.starting
    0x87155e69, // prep.xp_disks
    0x19d32f03, // profile.add
    0xf7030016, // profile.add.detail
    0x5951406b, // profile.add.detail_linux
    0x0ed7f0df, // profile.arch_warning
    0xc61083bb, // profile.badge
    0x4d6d6420, // profile.badge_incomplete
    0x18d4431a, // profile.cancel
    0xe272fe39, // profile.delete.confirm
    0xde446e2e, // profile.delete.keep
    0x92e5d06b, // profile.delete.question
    0x584ba887, // profile.delete.title
    0x919ddef5, // profile.edition_missing
    0xac80d0a1, // profile.editor.new
    0x6f2b3c09, // profile.editor.subtitle
    0x39676f88, // profile.editor.subtitle_linux
    0xde080639, // profile.editor.title
    0x49862935, // profile.field.bypass_ram
    0x1513f82f, // profile.field.bypass_secure_boot
    0x50329252, // profile.field.bypass_tpm
    0xa13d2795, // profile.field.classic_start
    0xa6b11e2b, // profile.field.computer
    0x67b0880e, // profile.field.disable_uac
    0x8015202b, // profile.field.disable_wer
    0xe8e3e9d4, // profile.field.display
    0x9c409bd4, // profile.field.edition
    0xf69d863d, // profile.field.hide_outlook_express
    0x1d1b0b5d, // profile.field.key
    0x40eff7a3, // profile.field.keyboard
    0x7890b224, // profile.field.language
    0x06522829, // profile.field.local_account
    0x383d1338, // profile.field.locale
    0x8dd802a5, // profile.field.name
    0x805be4da, // profile.field.network_location
    0x2852f76e, // profile.field.no_autorun
    0xe31c9ca0, // profile.field.no_balloon_tips
    0xa22f6351, // profile.field.no_hibernation
    0xe80859fc, // profile.field.no_network
    0x1cafbf72, // profile.field.no_sidebar
    0xc6afb682, // profile.field.no_welcome_center
    0x7cebcb94, // profile.field.org
    0x367e27db, // profile.field.password
    0xf251a013, // profile.field.protect_pc
    0xf04168d9, // profile.field.remember_key
    0x228b6a96, // profile.field.show_extensions
    0x57fc2cd0, // profile.field.show_hidden
    0xea43708d, // profile.field.skip_games
    0xf47b87f8, // profile.field.skip_msn
    0x66eb02dc, // profile.field.systems
    0xacd6085f, // profile.field.theme
    0xc97f214d, // profile.field.timezone
    0xa0db31f9, // profile.field.user
    0x040f6291, // profile.field.user2
    0x39ab14e9, // profile.file.detail
    0x0922c403, // profile.help.bypass
    0x2218a4ea, // profile.help.classic_start
    0x46264466, // profile.help.computer
    0x8b080fad, // profile.help.disable_uac
    0xa0ced3e4, // profile.help.disable_wer
    0xdfc03dcf, // profile.help.display
    0xbe0d347f, // profile.help.edition
    0x08ba0e0c, // profile.help.hide_outlook_express
    0xcca2e39e, // profile.help.key
    0x10f18736, // profile.help.keyboard
    0x8e773749, // profile.help.language
    0x7425bece, // profile.help.local_account
    0x69474139, // profile.help.locale
    0x33f53224, // profile.help.name
    0x6dc95247, // profile.help.network_location
    0x7e4da903, // profile.help.no_autorun
    0x2248d9c3, // profile.help.no_balloon_tips
    0x65b474ac, // profile.help.no_hibernation
    0x7cf8eb69, // profile.help.no_network
    0xdda310d3, // profile.help.no_sidebar
    0x69a6ce19, // profile.help.no_welcome_center
    0x324f097b, // profile.help.org
    0xfc88614e, // profile.help.password
    0x4d51ba86, // profile.help.protect_pc
    0xa2076c1c, // profile.help.remember_key
    0xa9724261, // profile.help.show_extensions
    0x2872a44f, // profile.help.show_hidden
    0xe0f94590, // profile.help.skip_games
    0xfb1b5659, // profile.help.skip_msn
    0xd953794f, // profile.help.systems
    0x65191388, // profile.help.theme
    0xf3284598, // profile.help.timezone
    0xb1ef9f14, // profile.help.user
    0x423788d2, // profile.help.user2
    0x5f1c9d40, // profile.key.delete
    0x4c0a173f, // profile.key.edit
    0x4ce11c3a, // profile.key.import
    0xb6f66d52, // profile.key.use
    0xadbb5231, // profile.manual.detail
    0xeea04301, // profile.missing.key
    0x02d02387, // profile.missing.password
    0xb6210153, // profile.problem.bad_characters
    0x568a5598, // profile.problem.bad_key_format
    0x94cec6cc, // profile.problem.duplicate
    0x45a02e98, // profile.problem.empty
    0xa0ced9c8, // profile.problem.only_digits
    0x81e142e7, // profile.problem.reserved_name
    0xa1001efc, // profile.problem.same_as_user
    0x842984ea, // profile.problem.too_long
    0xeb02a17f, // profile.row.detail
    0x134a2641, // profile.row.help
    0x4c6f4f3d, // profile.save
    0x9f87b247, // profile.save_failed
    0xd52428ac, // profile.section.extras
    0xea748758, // profile.summary
    0x803f740e, // profile.value.auto
    0x74eb2ac4, // profile.value.edition_manual
    0x94a66e59, // profile.value.network_home
    0x0742279f, // profile.value.network_public
    0xce89b51b, // profile.value.network_work
    0x7de03296, // profile.value.protect_off
    0x6c457fe8, // profile.value.protect_recommended
    0x9310ce39, // profile.value.protect_updates
    0x5f697fae, // profile.value.same_language
    0x9a227b9e, // profile.value.same_locale
    0x791012ad, // profile.value.setup_asks
    0xdb76978d, // profile.value.systems_all
    0xd11c4254, // profile.value.systems_linux
    0x95a3a608, // profile.value.systems_only
    0xfc2781a3, // profile.value.systems_windows
    0x84c34547, // profile.value.theme_basic
    0xcb765071, // profile.value.theme_classic
    0x87382378, // profile.value.theme_default
    0x8b09c640, // profile.xp_ini.detail
    0x50256306, // server.belongs_in
    0xb1aaa349, // server.blocked_ia64
    0x88ac4304, // server.client_in_server_folder
    0x2a085b63, // server.core
    0xab736064, // server.desktop
    0x167e4e9f, // server.editions
    0x57bd8b78, // server.in_client_folder
    0x80dcc372, // server.nvme_hint
    0x3474f2b3, // server.section
    0xdd3ef586, // server.section.detail
    0xd46db841, // server.setup
    0x4f9583c2, // splash.images
    0x35ce4a04, // splash.loading
    0x790f2c74, // splash.starting
    0x21b7d2fc, // summary.answer_file
    0x793c0723, // summary.boot_pe
    0xae5be5f9, // summary.boot_source
    0x4c709436, // summary.disk
    0xc97409c2, // summary.driver_inventory
    0xacfd5f5a, // summary.drivers
    0x1d60f5df, // summary.edition
    0x99bfe691, // summary.edition_value
    0x5fb166d7, // summary.error
    0xf810572f, // summary.esp_guard
    0x4e8be16e, // summary.esp_guard_label
    0xc7a77b9c, // summary.image
    0xfbb93592, // summary.inf_count
    0xa67ee0dd, // summary.iso_case
    0x23a9357f, // summary.iso_inspection
    0x3ed2d6ee, // summary.method
    0x25344415, // summary.native_case
    0x34dc4dbb, // summary.no_answer_files
    0xe8143028, // summary.no_drivers
    0xeefafc17, // summary.nt52_limits
    0x92637c78, // summary.preparation
    0xb2783d3b, // summary.secure_boot_badge
    0xfedbcf61, // summary.secure_boot_detail
    0x60a25811, // summary.secure_boot_line1
    0x5da25358, // summary.secure_boot_line2
    0x4e7ff9d0, // summary.secure_boot_linux_line1
    0xaf249476, // summary.secure_boot_title
    0x46c71b92, // summary.source
    0xa12382cb, // summary.subtitle
    0xa6031186, // summary.system
    0x9be682aa, // summary.target_support
    0xd56f468f, // summary.title
    0x0c17e473, // summary.unavailable
    0x38417087, // summary.usb
    0xe1d21ed0, // summary.user_drivers
    0xb5aa5b1c, // summary.user_drivers_count
    0x39f92475, // summary.user_drivers_folder
    0x8e042d81, // summary.vista_case
    0xe9c433ae, // summary.vista_case_nocsm
    0xf1becdee, // summary.vista_csmwrap
    0xa0987638, // summary.vista_support
    0x1e3154b1, // summary.vista_usb
    0xf657c7a8, // summary.w2k_limits
    0xac5a69f9, // summary.xp_csmwrap
    0xe262ce65, // summary.xp_disk
    0xedd282b9, // summary.xp_preparation
    0xa87889c3, // summary.xp_sif_merged
    0x6dfb98bd, // summary.xp_source
    0x1a62b0c1, // theme_edit.blocked
    0xbe71b5e9, // theme_edit.cancel
    0xf3bd28a8, // theme_edit.contrast.bad
    0x4abc69ff, // theme_edit.contrast.ok
    0xa984d2ef, // theme_edit.element.accent
    0xbe6f7b46, // theme_edit.element.accent_pressed
    0x252b9348, // theme_edit.element.accent_soft
    0xc4870795, // theme_edit.element.background
    0x3ff2f6af, // theme_edit.element.border
    0x345238a7, // theme_edit.element.border_strong
    0x2c1c55c6, // theme_edit.element.danger
    0xfc31cce7, // theme_edit.element.danger_soft
    0xdcb0986d, // theme_edit.element.disabled
    0x7c46f8e5, // theme_edit.element.disabled_text
    0xcf86e501, // theme_edit.element.faint
    0x77ab421f, // theme_edit.element.field
    0xf96abb98, // theme_edit.element.header
    0x047541b8, // theme_edit.element.muted
    0xe6233397, // theme_edit.element.on_accent
    0xa043a10a, // theme_edit.element.on_pad
    0x76e2038d, // theme_edit.element.pad_x
    0xf0ee183d, // theme_edit.element.panel
    0x55d45a8d, // theme_edit.element.panel_alt
    0x8bf2ff0c, // theme_edit.element.selected
    0x437be4a8, // theme_edit.element.success
    0x3ad3c845, // theme_edit.element.success_soft
    0x06d1e596, // theme_edit.element.text
    0x839979d7, // theme_edit.element.warning
    0xb8348be0, // theme_edit.element.warning_soft
    0x64495800, // theme_edit.field.base
    0xbbec99e5, // theme_edit.field.blue
    0x263edb20, // theme_edit.field.color
    0xb903293f, // theme_edit.field.element
    0xef484324, // theme_edit.field.green
    0xa542210e, // theme_edit.field.name
    0xb9ed4334, // theme_edit.field.red
    0x7286db3b, // theme_edit.help.base
    0x20988a31, // theme_edit.help.channel
    0x0d50e179, // theme_edit.help.color
    0x730e824e, // theme_edit.help.element
    0xa2a3cf75, // theme_edit.help.name
    0xa73c6853, // theme_edit.open
    0x1b284626, // theme_edit.open.detail
    0x76aa10ff, // theme_edit.pair
    0xc67214a1, // theme_edit.preview.button
    0xbf9046b5, // theme_edit.preview.disabled
    0x7aac066b, // theme_edit.preview.row
    0x0367032e, // theme_edit.preview.text
    0xef386ff9, // theme_edit.preview.title
    0xd628c45e, // theme_edit.reset
    0xc9bf181a, // theme_edit.save
    0x24ddcf0a, // theme_edit.save_failed
    0x15d38e5a, // theme_edit.saved
    0x90ebe073, // theme_edit.subtitle
    0xeec63a47, // theme_edit.title
    0x75bb3dee, // utilities.shell.desc
    0x5242a903, // utilities.shell.title
    0x30ddf187, // utility.unavailable
    0xd1d3d8e5, // xp_prep.checking
    0x72ed5eb8, // xp_prep.choose_disk
    0x8a502c84, // xp_prep.copy_verify
    0xe5b1ef16, // xp_prep.environment
    0x6e3859d3, // xp_prep.loading
    0xb07b1d15, // xp_prep.starting
};

/// False for strings only the UEFI menu shows (left out of the BIOS Core).
pub const bios = [_]bool{
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
};

/// The BIOS Core's strings are the first bios_count keys.
pub const bios_count = 327;

pub const english = [_][]const u8{
    "Experimental",
    "Ready",
    "Recommended",
    "Tested in VM",
    "Unavailable",
    "The selected Legacy backend returned an error.",
    "Boot method failed: {0}",
    "Hardware & SMART",
    "Loading environment",
    "Loading startup files - {0}%",
    "No images: {0}",
    "Loading Windows Setup into memory. Keep the USB drive connected.",
    "Loading Windows Setup - {0}%",
    "Reading the installer from USB",
    "Starting Windows Setup",
    "Windows Setup could not be loaded.",
    "The prepared installation files were kept on the USB drive.",
    "Restart to try again, or press Esc to return to the USOS menu.",
    "Windows Setup - start failed",
    "Starting Windows installer",
    "Continue XP",
    "A Windows XP installation was prepared on a target disk.",
    "After Text Mode has copied files and restarted, press Enter.",
    "USOS will verify that disk and restore its startup code.",
    "Then remove USOS and start the target disk to continue Setup.",
    "Windows XP - continue installation",
    "Beta builds",
    "Whistler, Longhorn and other builds",
    "DOS systems and legacy boot images",
    "Linux installers and live systems",
    "Power",
    "Restart, shut down or enter firmware setup",
    "Utilities",
    "Diagnostics, recovery and firmware tools",
    "Install and repair Microsoft Windows",
    "Sun",
    "Mon",
    "Tue",
    "Wed",
    "Thu",
    "Fri",
    "Sat",
    "WinPE helper image is damaged (checksum mismatch). Run Repair in the USOS installer.",
    "WinPE helper image missing (needed for Vista/Windows 7). Run Repair in the USOS installer.",
    "Delete partitions and install",
    "All current data on the selected disk will be lost.",
    "Formatting and the installer then start automatically.",
    "Confirm disk preparation",
    "Disk {0} - {1} MiB - GPT",
    "Disk {0} - {1} MiB - {2}, partitions: {3}",
    "New layout: one active {0} partition, {1}, drive letter C:",
    "Install MS-DOS on a disk",
    "Started from USB, C: is a RAM disk.",
    "Changes made in this session are lost when the computer is turned off.",
    "Start DOS and programs from USB",
    "Run programs from USB or install DOS on a disk",
    "No suitable target disk was found.",
    "Choose a disk for the new FAT16 partition. The USB drive is excluded.",
    "USOS will create a new FAT32 partition. The installation USB drive is excluded.",
    "RAM repair keeps the system and partitions. The USB drive is excluded.",
    "Apply the RAM fix",
    "Patcher9x / RAM fix",
    "The system and partitions stay. Changed files are backed up first.",
    "Repairs the installation in C:\\WINDOWS, also after the first restart.",
    "Windows 98 RAM repair",
    "The remaining space stays unallocated.",
    "Existing partitions on this disk will be deleted.",
    "Size of the new partition",
    "New Windows 98 SE installation",
    "Repair RAM support in an installed Windows 98",
    "Install Windows 98 or repair its support for more RAM",
    "Blocked",
    "Switch it on to try again.",
    "built-in",
    "UEFI drivers the menu starts",
    "File: {0}",
    "Put each driver in its own folder: Drivers\\UEFI\\<Name>\\ (.efi + optional driver.ini)",
    "Loads on every computer (no [match])",
    "Does not match this computer",
    "Matches this computer",
    "Changes apply at the next start",
    "No drivers in Drivers\\UEFI",
    "Built-in \xc2\xb7 started for Windows setup from WORK",
    "Reads the NTFS partitions when Windows setup starts.",
    "The menu itself reads DATA with its own reader.",
    "Off",
    "On",
    "Secure Boot off: no signature check",
    "Secure Boot on: checked when loaded",
    "Secure Boot on: signature verified",
    "Blocked: the menu stopped while it started",
    "Same file as another driver",
    "Failed: {0}",
    "Failed",
    "File missing or unreadable",
    "Not for this computer",
    "Turned off",
    "Not an x64 EFI driver",
    "Requires Secure Boot off or a signature",
    "Started",
    "Drivers",
    "Enter/A switches it on or off (next start)",
    "Rename the folder (no = [ ] ;) to switch it here",
    "Only on ROG Ally and Steam Deck (SMBIOS)",
    "Type: {0}",
    "Build {0}",
    "Boot menu",
    "Automatic - recommended",
    "USOS selects the supported boot path for this image automatically.",
    "For this Windows ISO it currently resolves to the ISO method below.",
    "Transfers control to another bootloader instead of preparing the image itself.",
    "Useful when the selected media already contains its own compatible bootloader.",
    "Chainload",
    "Treats an IMG file as a complete disk image rather than an optical image.",
    "Use it for utilities or systems distributed as raw disk images.",
    "Disk image",
    "Loads the selected EFI application directly through UEFI LoadImage/StartImage.",
    "Use it for standalone .efi boot programs that do not need another loader.",
    "EFI - direct UEFI start",
    "Treats an IMG file as a legacy floppy image.",
    "Intended for DOS-era boot disks and small legacy diagnostic tools.",
    "Floppy image",
    "USOS chooses the best implemented boot method for the selected image.",
    "Choose an explicit method only when you intentionally want to force that path.",
    "Extracts Windows Setup from the ISO to the WORK partition.",
    "After preparation USOS restarts once and boots Windows Setup from WORK.",
    "ISO - force ISO preparation",
    "Presents a small image as memory-backed boot media for legacy software.",
    "Primarily intended for DOS and older utilities, not modern Windows installers.",
    "Memdisk",
    "Copies installation files to the selected Windows partition.",
    "After preparation, remove the USB drive and start the computer from that disk.",
    "Automatic - Windows Setup",
    "Boots a prepared Windows installation stored in a VHD or VHDX image.",
    "It is for virtual-disk images, not normal Windows installation ISO files.",
    "VHDBoot",
    "Starts a Windows PE/WIM image using a WIM-oriented boot path.",
    "Useful when the source is a WIM instead of a complete installation ISO.",
    "WIMBoot",
    "Starts Windows Setup directly from the ISO on DATA; nothing is copied to WORK.",
    "Boot files go to the target disk; the USOS stick's ESP is checked and restored.",
    "Windows Setup",
    "No supported image files were found in Images.",
    "Copy ISO, WIM, IMG, VHD, VHDX or EFI files into Images and try again.",
    "ISO, WIM, IMG, VHD, VHDX and EFI files are detected automatically",
    "Select image",
    "Shows mouse, touch and key events live. Press Esc twice to leave.",
    "Input test",
    "Back",
    "Boot method",
    "Cancel",
    "Confirm",
    "Continue",
    "Diagnostics",
    "Next",
    "Open",
    "Power",
    "Power off",
    "Run",
    "Scroll",
    "Select",
    "Size",
    "Start",
    "Summary",
    "Use",
    "USOS menu",
    "English",
    "Unknown distribution: USOS uses the ISO's own boot entry (unverified).",
    "32-bit image - needs 32-bit UEFI or BIOS mode (CSM)",
    "ARM64 image - it does not start on this PC",
    "Choose another image or start the PC in the matching firmware mode.",
    "No UEFI loader on this image - use BIOS mode (CSM)",
    "This image cannot start here",
    "Not Windows boot media",
    "Windows Setup",
    "Contents could not be read",
    "WinPE / rescue media",
    "WinPE",
    "This ISO has no Windows installation image (install.wim/esd).",
    "USOS starts it as WinPE; nothing is installed.",
    "Choose what you want to boot or service",
    "What do you want to start?",
    "Automatic (Chainload)",
    "Automatic (DOS Setup)",
    "Automatic (EFI)",
    "Automatic (ISO)",
    "Automatic (MS-DOS / Windows 3.x)",
    "Automatic (SliTaz Live)",
    "Automatic (VHDBoot)",
    "Automatic (WIMBoot)",
    "Automatic (Windows 2000 Setup)",
    "Automatic (Windows Setup)",
    "Automatic (XP staging)",
    "Automatic (UEFI preparation / XP via CSM)",
    "Automatic",
    "Chainload",
    "Disk image",
    "Floppy image",
    "No boot methods are configured for this system.",
    "Choose how the selected image should be started",
    "Boot method",
    "No supported image files were found. Copy a file to:",
    "No images found",
    "APM power-off is unavailable on this computer.",
    "Turn off the computer manually.",
    "Check the mouse, touchscreen and keys",
    "Restart",
    "Shut down",
    "Restart or shut down this computer",
    "Power",
    "Measured percentage, speed and time left appear during the file copy.",
    "USB / PARTUUID diagnostics - the screen is frozen for a photo",
    "[Diagnostics truncated - see the serial output]",
    "Starting environment",
    "Time left",
    "Ready - remove the USOS USB drive, then press Enter to power off.",
    "Do not disconnect the drive or turn off the computer.",
    "Next power-on: boot the target disk without USOS.",
    "Remove the USOS USB drive before powering off.",
    "Speed",
    "Starting environment",
    "Verifying target device",
    "Preparing workspace",
    "Copying files",
    "Verification and finalization",
    "Done",
    "Failed",
    "In progress",
    "Waiting",
    "Step {0} of {1}",
    "Preparing Windows installer",
    "Missing",
    "Available while Secure Boot is off",
    "Available only when USOS is started by shim (EFI\\BOOT\\BOOTX64.EFI)",
    "Secure Boot state and the USOS key on this computer",
    "On many boards Secure Boot needs CSM turned off.",
    "After turning Secure Boot on in the BIOS, install the default keys (Install default Secure Boot keys / Factory keys), including the Microsoft UEFI CA.",
    "Add the key now, before turning Secure Boot on: then the \"Verification failed\" screen never appears.",
    "db has no Microsoft UEFI CA, so shim will not start with Secure Boot on. Install the default keys in the BIOS settings.",
    "Add the key with Secure Boot on",
    "1. Start the computer from the USOS drive. At \"Verification failed\" press Enter once.",
    "2. In the blue MokManager screen choose Enroll key from disk -> USOS_ESP -> USOS-KEY.cer.",
    "3. Choose Continue -> Yes -> Reboot. No password is needed.",
    "On a handheld tap each button once, do not hold it: a held button skips the screens.",
    "The USOS key is on this computer's deny list (MokListX), so it is not trusted.",
    "The USOS key is not saved on this computer",
    "The USOS key is saved on this computer",
    "Missing",
    "Saved",
    "The USOS key status is unknown",
    "The key file USOS-KEY.cer is missing from the drive",
    "Off",
    "On",
    "Secure Boot cannot be turned on until the default keys are restored in the BIOS settings.",
    "Secure Boot can be turned on (a platform key is installed).",
    "Present",
    "Remind on the home screen",
    "To remove it: MokManager -> Delete MOK. Resetting the Secure Boot keys in the BIOS does not remove it; only an NVRAM reset (CMOS clear, BIOS update, some \"load defaults\") does.",
    "Secure Boot: off",
    "Secure Boot: on",
    "Secure Boot: setup mode (no platform key)",
    "Secure Boot: not supported by this firmware",
    "Secure Boot",
    "Add the key",
    "Back to the menu",
    "USOS cannot find its Secure Boot key on this computer. Add it?",
    "Add",
    "Do you agree to save the USOS key in this computer's memory? It lets USOS start while Secure Boot is on.",
    "Only this computer is changed. The key can be removed later in MokManager (Delete MOK). Resetting the Secure Boot keys in the BIOS keeps it; only an NVRAM reset (CMOS clear, BIOS update, some \"load defaults\") removes it.",
    "Save the key?",
    "The firmware did not store the key. Use MokManager instead (Tools -> Secure Boot -> Add the key with Secure Boot on).",
    "The key was not saved",
    "Don't ask again",
    "You can add the key later in Tools -> Secure Boot.",
    "No",
    "Not now",
    "Without the USOS key, this computer does not start USOS while Secure Boot is on.",
    "Secure Boot is off right now, so the key can be saved here directly: no password and no MokManager.",
    "Open BIOS settings",
    "Key saved. You can now turn Secure Boot on in the BIOS settings.",
    "Key saved",
    "Secure Boot key",
    "Yes, save the key",
    "Copy images to {0}",
    "Images: {0}",
    "No image",
    "Ready",
    "Requires BIOS",
    "This system starts only in BIOS mode; USOS is running in UEFI mode.",
    "To use it, start the USB stick in Legacy BIOS (CSM) mode: pick its non-UEFI entry in the firmware boot menu.",
    "Requires UEFI",
    "This system starts only in UEFI mode; USOS is running in BIOS mode.",
    "To use it, start the USB stick in UEFI mode: pick its UEFI entry in the firmware boot menu.",
    "Unavailable",
    "No working boot backend supports this system yet.",
    "Select a system, distribution or utility group",
    "built-in",
    "in use",
    "Colours of this menu",
    "Enter/A applies it now and saves it on the stick",
    "This theme cannot be used: {0}",
    "Dark",
    "Default",
    "High contrast",
    "Light",
    "Retro (BIOS blue)",
    "Theme",
    "your theme",
    "The selected answer file is copied after the target safety check.",
    "No answer file",
    "Use the default setup options without a custom answer file.",
    "Choose an answer file or continue without one",
    "Unattended setup",
    "Answer files: not supported for Vista on UEFI yet",
    "Vista Setup on UEFI runs without your answer files and profiles for now; choose the manual installation.",
    "The .sif is merged into the automatic answer; disk, PAE and driver settings stay automatic. usos-xp.ini is not used.",
    "No answer file (manual installation)",
    "usos-xp.ini is not used: XP Setup asks for the name, product key and time zone.",
    "usos-xp.ini: {0}, {1}",
    "Automatic XP Setup with the accounts and computer name from usos-xp.ini. The product key is not shown.",
    "DOS programs from USB, file manager and command prompt",
    "Built-in: CPU, RAM, motherboard and disks",
    "No utility folders were found on this USOS drive.",
    "Create Utilities/<tool name>/Images on DATA, then run Update USOS.",
    "No utilities",
    "Please wait",
    "Please wait - keep the USB drive connected",
    "Start is not possible with these settings",
    "Prepare and chainload",
    "Start the EFI application",
    "Press Enter or click the button to start.",
    "Load the Windows ISO",
    "Start Linux",
    "Prepare native VHD/VHDX boot",
    "Build and boot the WIM environment",
    "Start WinPE",
    "Prepare the Windows XP installation",
    "Boot media preparation is complete.",
    "Starting EFI/BOOT from the prepared WORK partition...",
    "Starting chained bootloader",
    "Transferring control through UEFI LoadImage/StartImage...",
    "Starting EFI application",
    "USOS could not open the NTFS USOS_DATA volume.",
    "Images are read directly from DATA; ESP marker files are not used.",
    "DATA catalog unavailable",
    "EFI start failed",
    "This selection cannot start in the current firmware mode.",
    "Firmware mismatch",
    "Windows ISO start failed",
    "Linux ISO start failed",
    "The ISO file is too fragmented on DATA. Copy it to DATA again.",
    "USOS files on the stick are incomplete. Run Repair in the USOS installer.",
    "No Linux boot entry was found in this ISO.",
    "Preparation failed",
    "Secure Boot rejected the file: it is not signed by Microsoft or by an enrolled key.",
    "The operation stopped safely. Check the serial log if needed.",
    "The selected method has no working backend.",
    "Boot method unavailable",
    "XP preparation failed",
    "(empty)",
    "Delete",
    "Change",
    "Keys",
    "Off",
    "On",
    "Done",
    "Shift",
    "Space",
    "Choose a value",
    "Loading Windows Boot Manager...",
    "Saving the one-shot handoff state...",
    "Windows installer preparation is complete.",
    "Please wait. The Windows logo will appear shortly.",
    "Loading the NTFS driver...",
    "Preparing the Windows Setup handoff...",
    "Starting Windows Setup",
    "Transferring control to Windows Setup...",
    "Verifying install.wim and EFI boot files...",
    "Locating the prepared WORK partition...",
    "No mouse",
    "Detects the installer version and starts it directly from ISO in UEFI.",
    "WinPE 7 receives UEFI compatibility and optional Drivers/x64 packages in RAM.",
    "Windows ISO - WIMBoot UEFI",
    "Reading optional Windows 7 x64 driver packages",
    "Starting external PE10; the install source remains the selected Windows ISO",
    "Starting the hybrid ISO's own WinPE and Setup",
    "Loading boot-source boot.wim: {0}%",
    "Reading the selected Windows ISO",
    "Validating installation ISO",
    "Loading Windows boot files",
    "Starting Windows Setup",
    "Starting Windows from ISO",
    "Validating the installation ISO and resolving the boot source",
    "No implemented boot backend supports this selection.",
    "This system stays visible because its backend is planned.",
    "Firmware setup (BIOS/UEFI)",
    "Could not request firmware setup on the next restart.",
    "Firmware setup",
    "Not supported by this firmware",
    "Preparation environment ready",
    "Preparation request saved",
    "Return boot configured",
    "Starting preparation environment",
    "Starting XP disk selection",
    "+ Add a new profile",
    "A USOS profile: accounts, computer name, language and time zone for every Windows",
    "A USOS profile: user, computer name, language and time zone for the Linux installer; you always choose the disk",
    "The answer file has no settings for {0} media: Setup ignores it. Use a file made for this architecture.",
    "USOS profile",
    "Incomplete",
    "Cancel",
    "Delete the profile",
    "Keep the profile",
    "Delete the profile {0} from this stick?",
    "Delete profile",
    "Edition \"{0}\" is not on this ISO: Setup asks for the edition.",
    "New answer profile",
    "One profile for every Windows: USOS writes the answer file when the installation starts",
    "One profile for Windows and Linux: USOS writes the answer file when the installation starts",
    "Answer profile",
    "Windows 11: skip the RAM check",
    "Windows 11: skip the Secure Boot check",
    "Windows 11: skip the TPM check",
    "Classic Start menu",
    "Computer name",
    "Turn off UAC",
    "Turn off error reporting",
    "Screen resolution",
    "Edition",
    "Hide Outlook Express",
    "Product key ({0})",
    "Keyboard",
    "Windows language",
    "Local account",
    "Formats",
    "Profile name",
    "Vista/7: network location",
    "Turn off AutoRun",
    "No balloon tips",
    "Turn off hibernation",
    "Windows 11: set up without network",
    "Turn off Sidebar and gadgets",
    "No Welcome Center",
    "Organization",
    "Password",
    "Protection and updates",
    "Remember the key on this stick",
    "Show file extensions",
    "Show hidden files",
    "No games",
    "No MSN Explorer and Messenger",
    "Use for",
    "Theme",
    "Time zone",
    "User name",
    "Second user",
    "Answer file from the Unattended folder, used as it is",
    "For hardware below the Windows 11 requirements. Microsoft does not support such installations; feature updates may need the bypass again.",
    "XP: the Windows 2000 style Start menu for new users.",
    "1-15 characters A-Z a-z 0-9 and -, not only digits. Empty: USOS-XP on XP, a name chosen by Setup on newer Windows.",
    "Vista and 7: User Account Control off. Less safe: every program of an administrator runs with full rights.",
    "Vista and newer: Windows Error Reporting stays off (no problem reports are sent).",
    "XP and Server 2003: 32-bit colour at this resolution when the display driver offers it. Automatic: unchanged; without a display driver (the VGA driver, e.g. through CSMWrap) Windows keeps its basic mode.",
    "Edition Setup installs, matched against the images of the chosen ISO (also across languages; Server: Core or Desktop Experience). Empty or not on the ISO: Setup shows its edition list.",
    "XP and Server 2003: the Outlook Express shortcuts are removed; the program itself stays.",
    "Product key for {0} (XXXXX-XXXXX-XXXXX-XXXXX-XXXXX). Empty: Setup asks for it or offers the edition list.",
    "Keyboard layout of Windows. Same as the formats: the default keyboard of that language.",
    "Language of Setup and of Windows; the installation media must contain it. Automatic: Setup asks.",
    "Windows 8 and newer: create the accounts locally and hide the Microsoft account pages.",
    "Date, time, number and currency formats.",
    "Name of the profile on this stick: 1-32 characters A-Z a-z 0-9, space, . _ -",
    "Vista and 7: answer to the network location page. Work or Home: a private network; Public: the strictest firewall.",
    "AutoRun and AutoPlay stay off on every drive, USB sticks and CDs included (NoDriveTypeAutoRun).",
    "XP and Server 2003: no balloon tips in the notification area; XP also skips the \"Tour Windows XP\" prompt.",
    "Vista and 7: no hibernation and no hybrid sleep; the disk space of hiberfil.sys is freed.",
    "Windows 11: finish the setup without a network connection (BypassNRO).",
    "Vista: Windows Sidebar, 7: desktop gadgets, turned off by policy.",
    "Vista: the Welcome Center does not open at every logon.",
    "Optional: up to 64 characters, without \" % ^ & | < >",
    "Password of the accounts; empty means no password. It is stored as plain text on the stick.",
    "Answer to the \"Help protect Windows\" page (Vista and newer). Off: no automatic updates until you turn them on.",
    "Off: the key is used until this computer restarts and is never written to the stick.",
    "Explorer shows file name extensions such as .exe (for every new user).",
    "Explorer shows hidden files and folders (for every new user); protected system files stay hidden.",
    "XP: the games are not installed. Vista and 7: the Games feature is turned off during Setup.",
    "XP and Server 2003: MSN Explorer and Windows Messenger are not installed.",
    "The systems whose answer screen offers this profile. Profiles saved without this setting are offered for every Windows, never for Linux.",
    "Theme of new users. XP: Windows Classic instead of Luna. 7: Windows Classic or Windows 7 Basic.",
    "Automatic: the default of the installation media.",
    "First local account, an administrator: 1-20 characters A-Z a-z 0-9 . _ - and space.",
    "Optional second administrator account.",
    "Delete",
    "Edit",
    "Import",
    "Use",
    "Setup asks every question itself; no profile or file is used",
    "No product key for {0}: Setup stops on the product key page. Edit the profile (X) and enter the key.",
    "{0} needs a password of at least 7 characters with three of: capitals, small letters, digits, symbols. Without one Setup stops on the Administrator password page.",
    "It contains characters that are not allowed here.",
    "A product key has the form XXXXX-XXXXX-XXXXX-XXXXX-XXXXX.",
    "A profile with this name exists already.",
    "This field is required.",
    "A computer name cannot be only digits.",
    "This is the name of a built-in Windows account.",
    "The second user must differ from the first.",
    "Too long.",
    "{0}, {1}",
    "A USOS profile, turned into the answer file for this Windows when the installation starts. The target disk is always chosen in Setup.",
    "Save",
    "The profile could not be saved on the stick:",
    "Appearance and extras",
    "Profile {0}: {1} ({2})",
    "Automatic",
    "Type manually\xe2\x80\xa6",
    "Home",
    "Public",
    "Work",
    "Off",
    "Recommended settings",
    "Important updates only",
    "Same as the language",
    "Same as the formats",
    "(Setup asks)",
    "Windows and Linux",
    "Every Linux installer",
    "Only {0}",
    "Every Windows",
    "Windows 7 Basic",
    "Windows Classic",
    "Default",
    "usos-xp.ini on DATA (read only); Import makes a USOS profile of it",
    "Belongs in Systems\\Windows\\{0}",
    "Itanium (IA64) image - it does not start on this PC",
    "This is a client Windows image. It belongs in Systems\\Windows\\{0}; it can still be started from here.",
    "Core",
    "Desktop Experience",
    "Server editions",
    "This is a Windows Server image. It belongs in Systems\\Windows\\{0}; it can still be started from here.",
    "This Setup has no built-in NVMe driver and this PC has an NVMe disk. Put the NVMe driver in DATA\\Drivers\\{0}\\Storage.",
    "Windows Server",
    "Server editions, 2008 to 2025",
    "Windows Server Setup",
    "Loading system images\xe2\x80\xa6",
    "Loading\xe2\x80\xa6",
    "Starting\xe2\x80\xa6",
    "Answer file",
    "Boot PE",
    "Boot source ISO",
    "Disk",
    "Driver inventory",
    "External drivers",
    "Edition",
    "{0} (image {1})",
    "Error",
    "Written to the target disk; the USOS stick's ESP is checked",
    "Boot files",
    "Image",
    "INF files: {0}; Windows checks the hardware match",
    "ISO case",
    "ISO inspection",
    "Method",
    "Windows Setup straight from the ISO (no copy to WORK)",
    "None found in {0}",
    "None in Drivers/x64; target USB 3 may be unavailable",
    "NT 5.2 (experimental): AHCI through GenAHCI on the system's StorPort; no NVMe/USB 3 driver in Setup",
    "Preparation",
    "Requires Secure Boot off",
    "Turn Secure Boot off in the firmware setup to use it",
    "This system starts through a legacy path (CSM, UefiSeven or an old Windows boot manager) that Secure Boot blocks.",
    "Turn Secure Boot off in the firmware setup, then start USOS again.",
    "This ISO has no boot loader signed for Secure Boot, so Secure Boot blocks it.",
    "Secure Boot is on",
    "Source",
    "Review the selected boot configuration",
    "System",
    "Target support",
    "Ready to start",
    "Unavailable",
    "USB",
    "Your drivers",
    "Drivers\\Windows 7: {0} INF used, {1} skipped",
    "Drivers\\{0}: {1} INF used, {2} skipped",
    "Vista SP2 x64 -> PE10; the installed system needs CSM",
    "Windows Vista without CSM: not supported yet (black screen) - enable CSM in the board settings",
    "Vista without CSM (experimental): legacy (MBR) install through CSMWrap, card with a legacy VBIOS",
    "KB2864202 + signed USB package + pre-Setup v11",
    "PE10 native USB; the target uses Vista USB v11",
    "Windows 2000 (experimental): no AHCI/NVMe/USB 3 driver for NT 5.0 (SATA in IDE mode), max. 4 GB RAM and 2 CPUs",
    "XP without CSM (experimental): CSMWrap, card with a legacy VBIOS, 1 core reserved",
    "Selected and confirmed in the next graphical screen",
    "UEFI; installed XP requires firmware CSM and MBR",
    "{0} (merged into the automatic answer)",
    "XP SP3 x86; ACPI / SATA / USB drivers; optional PAE boot entry",
    "Fix the contrast first: {0}",
    "Cancel",
    "Too little contrast: {0}",
    "All readability rules pass",
    "Accent",
    "Accent (pressed)",
    "Selection fill",
    "Background",
    "Borders",
    "Strong borders",
    "Danger, pad B",
    "Danger badge fill",
    "Disabled fill",
    "Disabled text",
    "Faint text",
    "Input fields",
    "Header and footer",
    "Secondary text",
    "Text on accent",
    "Letters on pad buttons",
    "Pad X",
    "Panels",
    "Hover and alternate panels",
    "Selection (older screens)",
    "Success, pad A",
    "Success badge fill",
    "Text",
    "Warning, pad Y",
    "Warning badge fill",
    "Base theme",
    "Blue",
    "Colour (#rrggbb)",
    "Element",
    "Green",
    "Theme name",
    "Red",
    "The built-in theme whose colours you start from.",
    "Left/Right: -/+ 8; the preview changes at once.",
    "Type #rrggbb, or step the red, green and blue values below.",
    "The menu colour to change; Left/Right steps through them.",
    "Name of the theme on this stick: 1-32 characters A-Z a-z 0-9 - _",
    "Create or edit a theme",
    "Start from a theme, change its colours with a live preview and contrast check, save it on this stick",
    "{0} on {1}",
    "Button",
    "Disabled",
    "Selected row",
    "Text and secondary text",
    "Preview",
    "Reset this element",
    "Save and use",
    "The theme could not be saved on the stick:",
    "Theme {0} saved on the stick and in use.",
    "Base theme, element, colour: the preview and the contrast check follow every change",
    "Theme editor",
    "Command line for EFI tools (flashers, testers) from DATA",
    "UEFI Shell",
    "This utility stays visible while its boot backend is unavailable.",
    "Checking the XP kernel, initramfs and USB drive identity",
    "Choosing the target disk",
    "Copying and verifying files",
    "Loading the preparation environment",
    "Loading the micro-Linux kernel from the USB drive",
    "The kernel is loading the XP environment; the disk selection follows",
};
