// Generated by installer/cmd/usos-i18n-gen from installer/internal/i18n/locales. Do not edit.
// English is built in; lang.bin on the ESP carries only the chosen language.

/// FNV-1a 32 of the key names stored in lang.bin (without the "boot." prefix).
pub const hashes = [_]u32{
    0x4c1c62c1, // lx.a_new_x_layout_will_be_created
    0x82f97f5e, // lx.adding_your_drivers
    0xcde86d7b, // lx.after_the_restart_x_setup_runs_on_its_own_up_to
    0xb2a68a12, // lx.all_buffered_writes_are_complete_closing_the_pre
    0xd0eebedd, // lx.all_partitions_systems_and_files_on_this_disk_wi
    0xbb9ba1eb, // lx.building_native_vhd_boot_environment
    0xf1004c9c, // lx.building_wim_boot_environment
    0x6176f51e, // lx.checking_bcd_boot_sdi_and_the_efi_fallback_boot
    0xd8b480aa, // lx.checking_boot_files
    0x76837b85, // lx.checking_selected_image_and_device_identity
    0xa5ea45fa, // lx.checking_target_safety
    0xc4495f07, // lx.checking_the_packages_in_drivers_for_windows_setup
    0x51a80680, // lx.checking_the_prepared_xp_target
    0xb777cf4e, // lx.checking_the_selected_bcd_and_efi_fallback_boot
    0x10e4c869, // lx.choose_a_disk_and_confirm_the_installation_befor
    0xf5ed5b98, // lx.choose_how_to_prepare_this_disk
    0x0b0d4245, // lx.closing_work_partition
    0x79bd5e74, // lx.committing_prepared_state_to_the_usb_drive
    0x1ff55f3a, // lx.comparing_the_copied_boot_wim_with_the_selected
    0xdc45e22c, // lx.computer_information_and_disk_health
    0x2d33f5ab, // lx.continuing_windows_xp_installation
    0x4044704a, // lx.copying_unattended_file
    0x1f871507, // lx.copying_wim_file
    0xc183fc7d, // lx.copying_windows_boot_manager_and_the_bcd_entry_f
    0x89a29dc1, // lx.copying_windows_boot_manager_bcd_boot_sdi_and_fo
    0x3d373e6a, // lx.cpu_memory_motherboard_bios_and_pci_devices
    0x4c075860, // lx.creating_a_fresh_ntfs_workspace_for_prepared_boo
    0x35afdafe, // lx.creating_a_fresh_ntfs_workspace_for_the_wim_boot
    0xfd5cc7ca, // lx.creating_a_small_ntfs_workspace_for_native_vhd_v
    0xc6641420, // lx.custom_sif_select_a_partition_in_xp_setup
    0xf1f16eb1, // lx.descriptions_reported_by_the_cpu_and_firmware
    0x3a4143a7, // lx.details_x_y_of_z
    0x21ef2e28, // lx.detect_newly_connected_devices
    0xcd2fe28b, // lx.detecting_disks
    0x1a755ab8, // lx.detecting_disks_no_installation_changes_have_sta
    0x0366a7d5, // lx.detecting_usos_partitions
    0x6d3ee2fe, // lx.device_guard_runs_before_the_first_destructive_o
    0x94ae85fb, // lx.disk_x
    0xf0f119eb, // lx.disks_smart
    0xb68b6f2a, // lx.disks_smart_2
    0xd50e6346, // lx.enumerating_disks_and_validating_the_selected_x
    0x6ef0db1f, // lx.erase_all_data_and_prepare_a_new_x_installation
    0x93990299, // lx.erase_all_data_on_this_disk
    0xf33b0401, // lx.file_count_total_size_and_prepared_state_verifie
    0x4c372cd1, // lx.file_detection_does_not_verify_whether_a_system
    0xa07d7bcd, // lx.finalization_complete
    0x2bdf6c73, // lx.finishing_work_writes_before_closing_the_prepare
    0x88ba9af3, // lx.flushing_to_disk
    0x0660182a, // lx.format_entire_disk
    0xe85b755e, // lx.formatting_work
    0x7cf40d37, // lx.full_report
    0x0a8beb0d, // lx.full_smart_report
    0xb5de91a5, // lx.further_details_omitted_from_this_view
    0x75d932c4, // lx.hardware_information
    0x0d14da67, // lx.hardware_smart
    0x3fc155ac, // lx.identity_attributes_and_error_history_no_additio
    0x6cc43056, // lx.initializing_keyboard_and_mouse
    0x34d9903d, // lx.initializing_only_the_storage_stack_needed_for_p
    0xa600211f, // lx.inspecting_disk
    0x8caa6891, // lx.install_x_in_unallocated_space
    0x06da9dd2, // lx.keep_existing_partitions
    0x8173ebb9, // lx.keep_the_usos_usb_drive_connected_setup_will_sta
    0x752c33ab, // lx.loading_the_selected_boot_image_from_ntfs
    0x65fc5619, // lx.measured_byte_progress_transfer_speed_and_eta
    0xe0764ec1, // lx.measured_byte_progress_transfer_speed_and_eta_ar
    0xd738a5be, // lx.models_serial_numbers_capacity_and_health_report
    0x4bcbac7d, // lx.mounting_boot_iso
    0x488a7c63, // lx.mounting_the_verified_efi_system_partition
    0x8569c9b4, // lx.move
    0xc9d96a0d, // lx.new_xpsetup_installer_partition_2_gib
    0x399e2996, // lx.no_disks_detected
    0x2be3334f, // lx.no_separate_xpsetup_partition_will_remain
    0x76d8d357, // lx.no_unattended_file_selected_skipped
    0xe5d5307c, // lx.one_partition_for_windows_and_automatic_setup
    0x02b9eb81, // lx.opening_data_partition
    0x03527491, // lx.opening_the_hardware_panel
    0x15fd9aab, // lx.opening_usos_configuration
    0x52531d29, // lx.opening_vhd_boot_environment
    0xfacb44d6, // lx.opening_wim_boot_environment
    0x50ff1525, // lx.opening_work
    0xefeb1f45, // lx.other_partitions_will_be_preserved
    0x468ea032, // lx.other_partitions_x
    0xac974e50, // lx.partitions_x_unallocated_approx_y_mib
    0x49e06b77, // lx.pgup_pgdn_or_mouse_wheel
    0xa0ce4ed4, // lx.please_wait_keep_the_usos_usb_drive_connected
    0xa46d636e, // lx.preparation_environment_started
    0xfc3ef41c, // lx.preparation_stopped
    0x27c6a2d4, // lx.prepare_windows_xp_installation
    0x702336a3, // lx.preparing_the_windows_partition_and_installation
    0xa3706ee2, // lx.preparing_uefi_startup_and_usb_drivers
    0xade2b7b3, // lx.preparing_windows_7
    0x309b72dd, // lx.proceed
    0x67123194, // lx.publishing_phase_prepared_after_boot_files_are_d
    0xc5abf57e, // lx.publishing_phase_prepared_after_file_data_is_dur
    0xea0a2936, // lx.publishing_phase_prepared_after_wim_data_is_dura
    0x59d755d9, // lx.read_the_current_values_again
    0xe046b1f1, // lx.reading_cpu_memory_firmware_and_pci_devices
    0x3729d0e9, // lx.reading_detected_disk_identities
    0x29ce53c7, // lx.reading_drive_identity_and_smart
    0x24918f79, // lx.reading_hardware_information
    0xad3209bf, // lx.reading_partitions_free_space_and_system_files
    0x59e09a65, // lx.reading_smart
    0x02396991, // lx.refresh_disk_list
    0xe4654156, // lx.refresh_smart
    0xa68b2644, // lx.remove_usos_usb_then_press_enter_to_power_off
    0xd41bf4b1, // lx.resolving_esp_data_and_work_by_partuuid
    0x453d5268, // lx.restart_the_computer
    0xb3a94cf0, // lx.restarting_to_windows_setup
    0x3de62306, // lx.return_to_disk_selection
    0xab419094, // lx.return_to_hardware_smart
    0xa94cd388, // lx.return_to_the_disk_list
    0x105ce7f4, // lx.return_to_the_smart_table
    0x566d34fc, // lx.return_to_usos
    0x3d85ff13, // lx.review_the_selected_disk_and_confirm_the_operati
    0x6bc3168c, // lx.s_n_x
    0x083c7357, // lx.select_a_disk_to_read_its_identity_and_health_in
    0x869ff39f, // lx.select_another_disk
    0xe12d4bdc, // lx.select_the_disk_for_x
    0x03f7a948, // lx.serial_number_x
    0x43ce6a76, // lx.size_x_gib
    0xb383cfc4, // lx.smart_is_not_enabled_or_changed_automatically
    0x3d3572c5, // lx.some_usb_bridges_and_virtual_disks_do_not_expose
    0x90d7f51a, // lx.starting_device_verification
    0xc959a35a, // lx.starting_installer
    0xde01c69b, // lx.status_in_use_formatting_is_blocked
    0x6851324e, // lx.status_not_currently_in_use
    0x5fd74519, // lx.system_information
    0xa2da7700, // lx.system_information_2
    0xb27e1e94, // lx.the_boot_media_copy_will_start_next
    0x2360a355, // lx.the_computer_will_continue_installation_from_thi
    0xc7a80cf7, // lx.the_disk_will_only_be_changed_after_your_confirm
    0x1250862f, // lx.the_existing_xpsetup_partition_will_be_formatted
    0xc4b74054, // lx.the_native_vhd_boot_manager_and_bcd_will_be_asse
    0x7383eba2, // lx.the_vhd_vhdx_remains_on_data_work_contains_the_v
    0xb35dc805, // lx.the_wim_boot_environment_will_be_assembled_next
    0x74abccc9, // lx.unknown_interface
    0x41cf0383, // lx.used_free_space_in_file_systems_unknown
    0xd5c6bc90, // lx.validating_free_space_mbr_state_and_the_xpsetup
    0xbc5ee284, // lx.validating_preparation_request
    0x8fd5d3aa, // lx.verified_boot_wim_bcd_boot_sdi_and_efi_boot_mana
    0xd146be75, // lx.verifying_boot_files
    0xb44b8921, // lx.verifying_disk_identity_and_work_ownership
    0xd779f437, // lx.verifying_file_count
    0x72508030, // lx.verifying_the_prepared_boot_path_before_committi
    0x827e27b3, // lx.verifying_the_staged_source_unmounting_media_and
    0x93b56f03, // lx.verifying_total_size
    0x9b309152, // lx.verifying_vhd_boot_files
    0x1a87a9e7, // lx.verifying_wim_file
    0xd2c4e12a, // lx.windows_c_x_gib_ntfs
    0xf4336aff, // lx.windows_xp
    0x1a650cd0, // lx.writing_autounattend_xml_to_the_prepared_work_pa
    0x95fc13b1, // lx.writing_autounattend_xml_to_the_wim_boot_environ
    0x659d851a, // lx.writing_buffered_data_to_the_usb_drive
    0x314dfa19, // lx.writing_prepared_files_to_the_usb_drive
    0x0a6101b3, // lx.writing_prepared_state
    0x6735ea3a, // lx.writing_the_vhd_boot_environment_to_the_usb_driv
    0x7922f68d, // lx.writing_the_wim_boot_environment_to_the_usb_driv
    0xe8d9b17d, // lx.x_confirm_installation
    0xe16bb36d, // lx.x_of_y_files
    0x02de0ef1, // lx.x_prepare_disk
    0x915c2db1, // lx.x_ready_to_install
    0xdca3696c, // lx.x_select_disk
    0xf8c61f6b, // lx.x_will_now_install_on_its_own
    0x2d25b64d, // lx.xp_kontynuacja_gotowa
};

pub const english = [_][]const u8{
    "A new {0} layout will be created.",
    "Adding your drivers",
    "After the restart, {0} Setup runs on its own up to the graphical setup wizard. Until then do not press any keys: the disk has already been chosen here.",
    "All buffered writes are complete; closing the prepared filesystem.",
    "All partitions, systems and files on this disk will be erased.",
    "Building native VHD boot environment",
    "Building WIM boot environment",
    "Checking BCD, boot.sdi and the EFI fallback boot manager.",
    "Checking boot files",
    "Checking selected image and device identity.",
    "Checking target safety",
    "Checking the packages in Drivers for Windows Setup.",
    "Checking the prepared XP target.",
    "Checking the selected BCD and EFI fallback boot manager.",
    "Choose a disk and confirm the installation before any changes.",
    "Choose how to prepare this disk.",
    "Closing WORK partition",
    "Committing prepared state to the USB drive.",
    "Comparing the copied boot.wim with the selected source.",
    "Computer information and disk health.",
    "Continuing Windows XP installation",
    "Copying unattended file",
    "Copying WIM file",
    "Copying Windows Boot Manager and the BCD entry for the selected VHD/VHDX.",
    "Copying Windows boot manager, BCD, boot.sdi and fonts.",
    "CPU, memory, motherboard, BIOS and PCI devices",
    "Creating a fresh NTFS workspace for prepared boot media.",
    "Creating a fresh NTFS workspace for the WIM boot environment.",
    "Creating a small NTFS workspace for native VHD/VHDX boot files.",
    "Custom SIF: select a partition in XP Setup.",
    "Descriptions reported by the CPU and firmware.",
    "Details {0}-{1} of {2}",
    "Detect newly connected devices",
    "Detecting disks",
    "Detecting disks. No installation changes have started.",
    "Detecting USOS partitions",
    "device_guard runs before the first destructive operation.",
    "Disk: {0}",
    "DISKS & SMART",
    "Disks & SMART",
    "Enumerating disks and validating the selected {0} target.",
    "Erase all data and prepare a new {0} installation",
    "ERASE ALL DATA ON THIS DISK",
    "File count, total size and prepared state verified.",
    "File detection does not verify whether a system works.",
    "Finalization complete",
    "Finishing WORK writes before closing the prepared partition.",
    "Flushing to disk",
    "Format entire disk",
    "Formatting WORK",
    "Full report",
    "Full SMART report",
    "Further details omitted from this view.",
    "HARDWARE INFORMATION",
    "HARDWARE & SMART",
    "Identity, attributes and error history; no additional disk query",
    "Initializing keyboard and mouse.",
    "Initializing only the storage stack needed for preparation.",
    "Inspecting disk",
    "Install {0} in unallocated space",
    "Keep existing partitions",
    "Keep the USOS USB drive connected. Setup will start automatically.",
    "Loading the selected boot image from NTFS.",
    "Measured byte progress, transfer speed and ETA.",
    "Measured byte progress, transfer speed and ETA are now available.",
    "Models, serial numbers, capacity and health reports",
    "Mounting boot ISO",
    "Mounting the verified EFI System Partition.",
    "Move",
    "New XPSETUP installer partition: 2 GiB.",
    "No disks detected.",
    "No separate XPSETUP partition will remain.",
    "No unattended file selected - skipped.",
    "One partition for Windows and automatic setup.",
    "Opening DATA partition",
    "Opening the hardware panel.",
    "Opening USOS configuration",
    "Opening VHD boot environment",
    "Opening WIM boot environment",
    "Opening WORK",
    "Other partitions will be preserved.",
    "(Other partitions: {0})",
    "Partitions: {0}; unallocated: approx. {1} MiB",
    "PgUp/PgDn or mouse wheel",
    "Please wait. Keep the USOS USB drive connected.",
    "Preparation environment started",
    "Preparation stopped",
    "Prepare Windows XP installation",
    "Preparing the Windows partition and installation files.",
    "Preparing UEFI startup and USB drivers.",
    "Preparing Windows 7",
    "Proceed",
    "Publishing phase=prepared after boot files are durable.",
    "Publishing phase=prepared after file data is durable.",
    "Publishing phase=prepared after WIM data is durable.",
    "Read the current values again",
    "Reading CPU, memory, firmware and PCI devices.",
    "Reading detected disk identities.",
    "Reading drive identity and SMART.",
    "Reading hardware information",
    "Reading partitions, free space and system files.",
    "READING SMART",
    "Refresh disk list",
    "Refresh SMART",
    "REMOVE USOS USB, THEN PRESS ENTER TO POWER OFF.",
    "Resolving ESP, DATA and WORK by PARTUUID.",
    "Restart the computer",
    "RESTARTING TO WINDOWS SETUP",
    "Return to disk selection",
    "Return to Hardware & SMART",
    "Return to the disk list",
    "Return to the SMART table",
    "Return to USOS",
    "Review the selected disk and confirm the operation.",
    "S/N: {0}",
    "Select a disk to read its identity and health information.",
    "Select another disk",
    "Select the disk for {0}.",
    "Serial number: {0}",
    "Size: {0} GiB",
    "SMART is not enabled or changed automatically.",
    "Some USB bridges and virtual disks do not expose SMART.",
    "Starting device verification",
    "STARTING INSTALLER",
    "Status: IN USE - formatting is blocked.",
    "Status: not currently in use.",
    "SYSTEM INFORMATION",
    "System information",
    "The boot media copy will start next.",
    "The computer will continue installation from this disk.",
    "The disk will only be changed after your confirmation.",
    "The existing XPSETUP partition will be formatted.",
    "The native VHD boot manager and BCD will be assembled next.",
    "The VHD/VHDX remains on DATA; WORK contains the verified boot manager and BCD.",
    "The WIM boot environment will be assembled next.",
    "Unknown interface",
    "Used/free space in file systems: unknown.",
    "Validating free space, MBR state and the XPSETUP reservation.",
    "Validating preparation request",
    "Verified boot.wim, BCD, boot.sdi and EFI boot manager.",
    "Verifying boot files",
    "Verifying disk identity and WORK ownership.",
    "Verifying file count",
    "Verifying the prepared boot path before committing state.",
    "Verifying the staged source, unmounting media and flushing writes.",
    "Verifying total size",
    "Verifying VHD boot files",
    "Verifying WIM file",
    "Windows C: {0} GiB NTFS.",
    "WINDOWS XP",
    "Writing Autounattend.xml to the prepared WORK partition.",
    "Writing Autounattend.xml to the WIM boot environment.",
    "Writing buffered data to the USB drive.",
    "Writing prepared files to the USB drive.",
    "Writing prepared state",
    "Writing the VHD boot environment to the USB drive.",
    "Writing the WIM boot environment to the USB drive.",
    "{0} - CONFIRM INSTALLATION",
    "{0} of {1} files",
    "{0} - PREPARE DISK",
    "{0} READY TO INSTALL",
    "{0} - SELECT DISK",
    "{0} will now install on its own",
    "XP - KONTYNUACJA GOTOWA",
};
