//go:build windows

// usos-installer is the Windows host installer for Universal Service OS. The
// UI is a native Win32 window (internal/ui); the icon, version info and the
// manifest (per-monitor DPI v2, common controls 6) come from
// rsrc_windows_amd64.syso, generated by cmd/usos-installer-rsrc.
//
//go:generate go run ../usos-installer-rsrc -out rsrc_windows_amd64.syso
package main

import (
	"fmt"
	"os"

	"github.com/snakex21/universal-service-os/installer/internal/buildinfo"
	"github.com/snakex21/universal-service-os/installer/internal/i18n"
	"github.com/snakex21/universal-service-os/installer/internal/install"
	"github.com/snakex21/universal-service-os/installer/internal/localupdate"
	"github.com/snakex21/universal-service-os/installer/internal/prefs"
	"github.com/snakex21/universal-service-os/installer/internal/repair"
	"github.com/snakex21/universal-service-os/installer/internal/ui"
	"github.com/snakex21/universal-service-os/installer/internal/uninstall"
	"github.com/snakex21/universal-service-os/installer/internal/winhost"
)

func main() {
	// The saved choice (%APPDATA%\USOS\installer.ini) wins; on first run the
	// Windows display language is preselected. The same language is the one
	// written to the USOS drive.
	prefsPath, _ := prefs.DefaultPath()
	i18n.SetLanguage(prefs.StartupLanguage(prefsPath))

	if err := run(prefsPath); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(prefsPath string) error {
	startupError := func(message string) error {
		return ui.Run(ui.Config{PrefsPath: prefsPath, StartupError: message})
	}
	logger, err := install.NewOperationLogger()
	if err != nil {
		return startupError(i18n.T("installer.startup.log_failed", err.Error()))
	}
	defer logger.Close()
	linkedBuild := buildinfo.Current()
	_ = logger.WriteLine(fmt.Sprintf("INSTALLER BUILD id=%s epoch=%d source_sha256=%s", linkedBuild.Display(), linkedBuild.Epoch, linkedBuild.SourceSHA256))

	backend := winhost.Backend{}
	installEngine, err := install.NewEngine(backend, logger)
	if err != nil {
		return startupError(i18n.T("installer.startup.install_engine_failed", err.Error()))
	}
	updateEngine, err := localupdate.NewEngine(backend, logger)
	if err != nil {
		return startupError(i18n.T("installer.startup.update_engine_failed", err.Error()))
	}
	repairEngine, err := repair.NewEngine(backend, logger)
	if err != nil {
		return startupError(i18n.T("installer.startup.repair_engine_failed", err.Error()))
	}
	uninstallEngine, err := uninstall.NewEngine(backend, logger)
	if err != nil {
		return startupError(i18n.T("installer.startup.uninstall_engine_failed", err.Error()))
	}

	return ui.Run(ui.Config{
		Disks:     winhost.Enumerator{},
		Installed: winhost.InstalledUSOSSource{},
		Install:   installEngine,
		Update:    updateEngine,
		Repair:    repairEngine,
		Uninstall: uninstallEngine,
		PrefsPath: prefsPath,
	})
}
