package i18n

import (
	"fmt"
	"regexp"
	"strings"
)

// Generated artifacts derived from the catalogs (see cmd/usos-i18n-gen).
// Paths are relative to the repository root.
const (
	ZigTablePath     = "src/i18n/boot_strings.zig"
	XPHeaderPath     = "tools/windows_xp_pae_strings.h"
	ZigFixtureLang   = "pl"
	ZigFixturePath   = "src/i18n/testdata/lang-pl.bin"
	generatedWarning = "Generated by installer/cmd/usos-i18n-gen from installer/internal/i18n/locales. Do not edit."
)

var zigIdentifier = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

// GenerateZigTable renders the English boot strings compiled into the EFI and
// the key enum used to read lang.bin.
func GenerateZigTable() ([]byte, error) {
	keys, catalog, err := prefixedEntries(Fallback, BootKeyPrefix)
	if err != nil {
		return nil, err
	}
	if len(keys) == 0 || len(keys) > 65535 {
		return nil, fmt.Errorf("unexpected boot key count %d", len(keys))
	}
	gaps, err := BootGlyphGaps(Fallback)
	if err != nil {
		return nil, err
	}
	if len(gaps) != 0 {
		return nil, fmt.Errorf("English boot strings must be renderable by font5x7: %v", gaps)
	}
	var b strings.Builder
	b.WriteString("// " + generatedWarning + "\n")
	b.WriteString("// English is built into the EFI; lang.bin on the ESP carries only the chosen language.\n\n")
	b.WriteString("pub const Key = enum(u16) {\n")
	for _, key := range keys {
		id := strings.ReplaceAll(strings.TrimPrefix(key, BootKeyPrefix), ".", "_")
		if !zigIdentifier.MatchString(id) {
			return nil, fmt.Errorf("boot key %s does not map to a Zig identifier", key)
		}
		b.WriteString("    " + id + ",\n")
	}
	b.WriteString("};\n\n")
	b.WriteString("/// Key names as stored in lang.bin (without the \"boot.\" prefix).\n")
	b.WriteString("pub const names = [_][]const u8{\n")
	for _, key := range keys {
		b.WriteString("    " + zigString(strings.TrimPrefix(key, BootKeyPrefix)) + ",\n")
	}
	b.WriteString("};\n\n")
	b.WriteString("pub const english = [_][]const u8{\n")
	for _, key := range keys {
		b.WriteString("    " + zigString(catalog[key]) + ",\n")
	}
	b.WriteString("};\n")
	return []byte(b.String()), nil
}

// GenerateXPHeader renders the English fallback strings compiled into pae.exe.
func GenerateXPHeader() ([]byte, error) {
	keys, catalog, err := prefixedEntries(Fallback, XPKeyPrefix)
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString("/* " + generatedWarning + " */\n")
	b.WriteString("/* English fallback; the chosen language is read from pae-strings.ini. */\n")
	for _, key := range keys {
		name := strings.ToUpper(strings.TrimPrefix(key, XPKeyPrefix))
		if !zigIdentifier.MatchString(strings.ToLower(name)) {
			return nil, fmt.Errorf("xp key %s does not map to a C identifier", key)
		}
		b.WriteString("#define USOS_XP_PAE_" + name + "_EN " + cWideString(catalog[key]) + "\n")
	}
	return []byte(b.String()), nil
}

func zigString(value string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, c := range []byte(value) {
		switch {
		case c == '"' || c == '\\':
			b.WriteByte('\\')
			b.WriteByte(c)
		case c >= 32 && c <= 126:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\x%02x", c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func cWideString(value string) string {
	var b strings.Builder
	b.WriteString(`L"`)
	for _, r := range value {
		switch {
		case r == '"' || r == '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case r >= 32 && r <= 126:
			b.WriteRune(r)
		case r <= 0xffff:
			fmt.Fprintf(&b, `\u%04x`, r)
		default:
			fmt.Fprintf(&b, `\U%08x`, r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
