package i18n

import (
	"fmt"
	"regexp"
	"strings"
)

// Generated artifacts derived from the catalogs (see cmd/usos-i18n-gen).
// Paths are relative to the repository root.
const (
	ZigTablePath      = "src/i18n/boot_strings.zig"
	ZigLinuxTablePath = "src/i18n/linux_strings.zig"
	XPHeaderPath      = "tools/windows_xp_pae_strings.h"
	WinPEHeaderPath   = "tools/windows_winpe_strings.h"
	ZigFixtureLang    = "pl"
	ZigFixturePath    = "src/i18n/testdata/lang-pl.bin"
	BootFontPath      = "src/gui/fonts/usos-font.bin"
	generatedWarning  = "Generated by installer/cmd/usos-i18n-gen from installer/internal/i18n/locales. Do not edit."
)

// uefiOnlyPrefixes are boot keys only the UEFI menu shows. The size-limited
// Legacy BIOS Core leaves their English text out (see src/i18n/lang_file.zig).
var uefiOnlyPrefixes = []string{
	"summary.", "handoff.", "iso.", "efi.", "chainload.", "error.", "action.",
	"help.win7_wimboot.", "power.firmware", "notice.backend.", "utility.",
	"prep.request_saved", "prep.return_boot", "prep.loader_ready", "prep.starting", "prep.xp_disks", "xp_prep.",
	"header.no_mouse", "splash.", "server.", "form.", "profile.", "theme_edit.",
	"utilities.shell.",
}

// LinuxKeyPrefix marks boot strings shown only by the micro-Linux framebuffer
// UI. Their English values are the exact literals the preparation scripts
// pass to usos-fb-ui, which translates them by English text (reverse lookup).
const LinuxKeyPrefix = BootKeyPrefix + "lx."

var zigIdentifier = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

// BootKeyHash is FNV-1a (32 bit) of a boot key name without the "boot."
// prefix. The Zig tables store these hashes instead of the names.
func BootKeyHash(name string) uint32 {
	hash := uint32(2166136261)
	for i := 0; i < len(name); i++ {
		hash ^= uint32(name[i])
		hash *= 16777619
	}
	return hash
}

// GenerateZigTable renders the English boot menu strings compiled into the
// EFI, the BIOS Core and usos-fb-ui, with the key enum and name hashes used
// to read lang.bin. boot.lx.* strings go to GenerateZigLinuxTable instead.
func GenerateZigTable() ([]byte, error) {
	return generateZigStrings(false)
}

// GenerateZigLinuxTable renders the micro-Linux boot strings (boot.lx.*).
func GenerateZigLinuxTable() ([]byte, error) {
	return generateZigStrings(true)
}

func generateZigStrings(linux bool) ([]byte, error) {
	allKeys, catalog, err := prefixedEntries(Fallback, BootKeyPrefix)
	if err != nil {
		return nil, err
	}
	keys := make([]string, 0, len(allKeys))
	for _, key := range allKeys {
		if strings.HasPrefix(key, LinuxKeyPrefix) == linux {
			keys = append(keys, key)
		}
	}
	if len(keys) == 0 || len(keys) > 65535 {
		return nil, fmt.Errorf("unexpected boot key count %d", len(keys))
	}
	hashes := map[uint32]string{}
	for _, key := range allKeys {
		name := strings.TrimPrefix(key, BootKeyPrefix)
		if other, dup := hashes[BootKeyHash(name)]; dup {
			return nil, fmt.Errorf("boot keys %s and %s share a name hash", key, other)
		}
		hashes[BootKeyHash(name)] = key
	}
	var b strings.Builder
	b.WriteString("// " + generatedWarning + "\n")
	b.WriteString("// English is built in; lang.bin on the ESP carries only the chosen language.\n\n")
	if !linux {
		ids := map[string]string{}
		b.WriteString("pub const Key = enum(u16) {\n")
		for _, key := range keys {
			id := strings.ReplaceAll(strings.TrimPrefix(key, BootKeyPrefix), ".", "_")
			if !zigIdentifier.MatchString(id) {
				return nil, fmt.Errorf("boot key %s does not map to a Zig identifier", key)
			}
			if other, dup := ids[id]; dup {
				return nil, fmt.Errorf("boot keys %s and %s map to the same Zig identifier", key, other)
			}
			ids[id] = key
			b.WriteString("    " + id + ",\n")
		}
		b.WriteString("};\n\n")
	}
	b.WriteString("/// FNV-1a 32 of the key names stored in lang.bin (without the \"boot.\" prefix).\n")
	b.WriteString("pub const hashes = [_]u32{\n")
	for _, key := range keys {
		fmt.Fprintf(&b, "    0x%08x, // %s\n", BootKeyHash(strings.TrimPrefix(key, BootKeyPrefix)), strings.TrimPrefix(key, BootKeyPrefix))
	}
	b.WriteString("};\n\n")
	if !linux {
		b.WriteString("/// False for strings only the UEFI menu shows (left out of the BIOS Core).\n")
		b.WriteString("pub const bios = [_]bool{\n")
		for _, key := range keys {
			used := true
			for _, prefix := range uefiOnlyPrefixes {
				if strings.HasPrefix(strings.TrimPrefix(key, BootKeyPrefix), prefix) {
					used = false
				}
			}
			fmt.Fprintf(&b, "    %v,\n", used)
		}
		b.WriteString("};\n\n")
	}
	b.WriteString("pub const english = [_][]const u8{\n")
	for _, key := range keys {
		b.WriteString("    " + zigString(catalog[key]) + ",\n")
	}
	b.WriteString("};\n")
	return []byte(b.String()), nil
}

// GenerateXPHeader renders the English fallback strings compiled into pae.exe.
func GenerateXPHeader() ([]byte, error) {
	keys, catalog, err := prefixedEntries(Fallback, XPKeyPrefix)
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString("/* " + generatedWarning + " */\n")
	b.WriteString("/* English fallback; the chosen language is read from pae-strings.ini. */\n")
	for _, key := range keys {
		name := strings.ToUpper(strings.TrimPrefix(key, XPKeyPrefix))
		if !zigIdentifier.MatchString(strings.ToLower(name)) {
			return nil, fmt.Errorf("xp key %s does not map to a C identifier", key)
		}
		b.WriteString("#define USOS_XP_PAE_" + name + "_EN " + cWideString(catalog[key]) + "\n")
	}
	return []byte(b.String()), nil
}

// GenerateWinPEHeader renders the English fallback strings compiled into
// the WinPE helpers (tools/windows_winpe_ui.h reads lang-winpe.ini).
func GenerateWinPEHeader() ([]byte, error) {
	keys, catalog, err := prefixedEntries(Fallback, WinPEKeyPrefix)
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString("/* " + generatedWarning + " */\n")
	b.WriteString("/* English fallback; the chosen language is read from EFI\\USOS\\lang-winpe.ini on the source ESP. */\n")
	for _, key := range keys {
		name := strings.TrimPrefix(key, WinPEKeyPrefix)
		if !zigIdentifier.MatchString(name) {
			return nil, fmt.Errorf("winpe key %s does not map to a C identifier", key)
		}
		b.WriteString("#define USOS_WINPE_" + strings.ToUpper(name) + "_KEY L\"" + name + "\"\n")
		b.WriteString("#define USOS_WINPE_" + strings.ToUpper(name) + "_EN " + cWideString(catalog[key]) + "\n")
	}
	return []byte(b.String()), nil
}

func zigString(value string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, c := range []byte(value) {
		switch {
		case c == '"' || c == '\\':
			b.WriteByte('\\')
			b.WriteByte(c)
		case c >= 32 && c <= 126:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\x%02x", c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func cWideString(value string) string {
	var b strings.Builder
	b.WriteString(`L"`)
	for _, r := range value {
		switch {
		case r == '"' || r == '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case r == '\n':
			b.WriteString(`\n`)
		case r >= 32 && r <= 126:
			b.WriteRune(r)
		case r <= 0xffff:
			fmt.Fprintf(&b, `\u%04x`, r)
		default:
			fmt.Fprintf(&b, `\U%08x`, r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
