#!/usr/bin/env python3
"""Generate losslessly compressed RGBA system icons for the Legacy BIOS Core.

UEFI can decode the full PNG files at runtime. Legacy Core has a fixed 256 KiB
slot and no BSS, so the build converts the same source PNGs to fixed 32x32 RGBA
pixels and stores their lossless RLE representation in the PM32 Core.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image
from legacy_rgba_rle import encode

ICON_WIDTH = 32
ICON_HEIGHT = 32
PIXEL_BYTES = ICON_WIDTH * ICON_HEIGHT * 4


def zig_identifier(stem: str) -> str:
    return "icon_" + "".join(ch if ch.isalnum() else "_" for ch in stem)


def rgba_bytes(path: Path) -> bytes:
    with Image.open(path) as source:
        image = source.convert("RGBA")
        if image.size != (ICON_WIDTH, ICON_HEIGHT):
            image = image.resize((ICON_WIDTH, ICON_HEIGHT), Image.Resampling.LANCZOS)
        data = image.tobytes()
    if len(data) != PIXEL_BYTES:
        raise RuntimeError(f"{path}: got {len(data)} RGBA bytes, expected {PIXEL_BYTES}")
    return data


def emit_array(name: str, data: bytes) -> list[str]:
    lines = [f"const {name}: [{len(data)}]u8 = .{{"]
    for offset in range(0, len(data), 32):
        chunk = data[offset : offset + 32]
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    lines.append("};")
    return lines


def generate(input_dir: Path, output: Path) -> None:
    icons = sorted(input_dir.glob("*.png"), key=lambda item: item.stem.lower())
    if not icons:
        raise RuntimeError(f"no PNG icons found in {input_dir}")

    rows: list[tuple[str, str, bytes]] = []
    for path in icons:
        rows.append((path.stem, zig_identifier(path.stem), encode(rgba_bytes(path))))

    lines = [
        "// Generated by tools/generate_legacy_icons.py. DO NOT EDIT.",
        'const std = @import("std");',
        "",
        f"pub const width: usize = {ICON_WIDTH};",
        f"pub const height: usize = {ICON_HEIGHT};",
        f"pub const byte_len: usize = {PIXEL_BYTES};",
        "",
        "pub fn get(id: []const u8) ?[]const u8 {",
    ]
    for stem, name, _ in rows:
        lines.append(f'    if (std.mem.eql(u8, id, "{stem}")) return {name}[0..];')
    lines.extend(["    return null;", "}", ""])

    for _, name, data in rows:
        lines.extend(emit_array(name, data))
        lines.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    packed_bytes = sum(len(data) for _, _, data in rows)
    print(f"[PASS] Legacy icons: {len(rows)} icons, {len(rows) * PIXEL_BYTES} RGBA bytes -> {packed_bytes} lossless RLE bytes -> {output}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    generate(args.input, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
