param(
    [string]$Stage1Path = 'zig-out/legacy-bios/stage1.bin',
    [string]$CorePath = 'zig-out/legacy-bios/core-slot.bin',
    [string]$OutputPath = 'installer/internal/payload/legacy_boot_generated.go'
)

$ErrorActionPreference = 'Stop'
$root = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
function Full([string]$Path) {
    if ([IO.Path]::IsPathRooted($Path)) { return [IO.Path]::GetFullPath($Path) }
    return [IO.Path]::GetFullPath((Join-Path $root $Path))
}

$stage1 = Full $Stage1Path
$core = Full $CorePath
$output = Full $OutputPath
foreach ($required in @($stage1, $core)) {
    if (-not (Test-Path -LiteralPath $required -PathType Leaf)) {
        throw "Missing Legacy BIOS artifact: $required"
    }
}

$stage1Bytes = [IO.File]::ReadAllBytes($stage1)
$coreBytes = [IO.File]::ReadAllBytes($core)
if ($stage1Bytes.Length -ne 440) { throw "Legacy Stage 1 must be exactly 440 bytes; got $($stage1Bytes.Length)" }
if ($coreBytes.Length -ne 262144) { throw "Legacy Core slot must be exactly 262144 bytes; got $($coreBytes.Length)" }

if ([Text.Encoding]::ASCII.GetString($coreBytes).Contains('[LEGACY_MENU_TEST]')) {
    throw 'Refusing to embed XP menu autotest Core in a production installer'
}

$sha = [Security.Cryptography.SHA256]::Create()
try {
    $stage1Hash = ([BitConverter]::ToString($sha.ComputeHash($stage1Bytes))).Replace('-', '')
    $coreHash = ([BitConverter]::ToString($sha.ComputeHash($coreBytes))).Replace('-', '')
} finally {
    $sha.Dispose()
}
$stage1Base64 = [Convert]::ToBase64String($stage1Bytes)
$coreBase64 = [Convert]::ToBase64String($coreBytes)

$content = @"
// Code generated by tools/generate_legacy_boot_payload.ps1; DO NOT EDIT.
package payload

const legacyStage1SHA256 = "$stage1Hash"
const legacyCoreSHA256 = "$coreHash"

const legacyStage1Base64 = "$stage1Base64"
const legacyCoreBase64 = "$coreBase64"
"@

$parent = Split-Path -Parent $output
if (-not (Test-Path -LiteralPath $parent -PathType Container)) {
    New-Item -ItemType Directory -Force -Path $parent | Out-Null
}
[IO.File]::WriteAllText($output, $content, [Text.UTF8Encoding]::new($false))
Write-Host "[PASS] Embedded Legacy Stage 1 SHA256=$stage1Hash"
Write-Host "[PASS] Embedded Legacy Core SHA256=$coreHash"
Write-Host "[PASS] Generated $output"
