/* Generated by installer/cmd/usos-i18n-gen from installer/internal/i18n/locales. Do not edit. */
/* English fallback; the chosen language is read from pae-strings.ini. */
#define USOS_XP_PAE_RESTART_PROMPT_EN L"Full memory (PAE) will be enabled after the computer restarts. Restart now?"
#define USOS_XP_PAE_TITLE_EN L"USOS XP"
